#pragma once

#define _VAT_ID_SPARE		(-1)
#define _VAT_DATA_TYPE_MAX  (2)

//1. Z Auto Focus(Mode1)
static int m1_nHandPosition[VAT_HAND_MAX] = { 
	IDC_EDIT_ZFOCUS_LOAD_TRAY_PP_STATUS, IDC_EDIT_ZFOCUS_UNLOAD_TRAY_PP_STATUS,
	IDC_EDIT_ZFOCUS_LOAD_TEST_PP_1_STATUS, IDC_EDIT_ZFOCUS_UNLOAD_TEST_PP_1_STATUS,
	IDC_EDIT_ZFOCUS_LOAD_TEST_PP_2_STATUS, IDC_EDIT_ZFOCUS_UNLOAD_TEST_PP_2_STATUS 
};

static int m1_nCamOffset[VAT_CAM_MAX][VAT_VISION_OFFSET_MAX] = {
	{ IDC_UPPERCAM_OFFSET_X_DATA_1,  IDC_UPPERCAM_OFFSET_Y_DATA_1 },		//LD Tray Pp
	{ IDC_LOERCAM_OFFSET_X_DATA_1,  IDC_LOERCAM_OFFSET_Y_DATA_1 },

	{ IDC_UPPERCAM_OFFSET_X_DATA_2,  IDC_UPPERCAM_OFFSET_Y_DATA_2 },		//UD Tray Pp
	{ IDC_LOERCAM_OFFSET_X_DATA_2,  IDC_LOERCAM_OFFSET_Y_DATA_2 },

	{ IDC_UPPERCAM_OFFSET_X_DATA_3,  IDC_UPPERCAM_OFFSET_Y_DATA_3 },		//Test Pp#1
	{ IDC_UPPERCAM_OFFSET_X_DATA_4,  IDC_UPPERCAM_OFFSET_Y_DATA_4 },
	{ IDC_LOERCAM_OFFSET_X_DATA_3,  IDC_LOERCAM_OFFSET_Y_DATA_3 },

	{ IDC_UPPERCAM_OFFSET_X_DATA_5,  IDC_UPPERCAM_OFFSET_Y_DATA_5 },		//Test Pp#2
	{ IDC_UPPERCAM_OFFSET_X_DATA_6,  IDC_UPPERCAM_OFFSET_Y_DATA_6 },
	{ IDC_LOERCAM_OFFSET_X_DATA_4,  IDC_LOERCAM_OFFSET_Y_DATA_4 },
};

static int m1_nCamStatus[VAT_CAM_MAX] = {
	IDC_ZFOCUS_UPPERCAM_STATUS_1, IDC_ZFOCUS_LOWERCAM_STATUS_1,									//LD Tray Pp
	IDC_ZFOCUS_UPPERCAM_STATUS_2, IDC_ZFOCUS_LOWERCAM_STATUS_2,									//UD Tray Pp
	IDC_ZFOCUS_UPPERCAM_STATUS_3, IDC_ZFOCUS_UPPERCAM_STATUS_4, IDC_ZFOCUS_LOWERCAM_STATUS_3,	//Test Pp#1
	IDC_ZFOCUS_UPPERCAM_STATUS_5, IDC_ZFOCUS_UPPERCAM_STATUS_6, IDC_ZFOCUS_LOWERCAM_STATUS_4,	//Test Pp#2
};

static int m1_nProgress[VAT_HAND_MAX] = {
	IDC_ZFOCUS_PROGRESS_1, IDC_ZFOCUS_PROGRESS_2, IDC_ZFOCUS_PROGRESS_3, IDC_ZFOCUS_PROGRESS_4, IDC_ZFOCUS_PROGRESS_5, IDC_ZFOCUS_PROGRESS_6,
};

static int m1_nPercent[VAT_HAND_MAX] = {
	CG_IDC_ZFOCUS_PROGRESS_PERCENT_1, CG_IDC_ZFOCUS_PROGRESS_PERCENT_2, CG_IDC_ZFOCUS_PROGRESS_PERCENT_3, 
	CG_IDC_ZFOCUS_PROGRESS_PERCENT_4, CG_IDC_ZFOCUS_PROGRESS_PERCENT_5, CG_IDC_ZFOCUS_PROGRESS_PERCENT_6,
};


//2. Cam Center Calibration(Mode2)
static int m2_nHandPosition[VAT_HAND_MAX] = { 
	IDC_EDIT_CAM_CENTER_CAL_LOAD_TRAY_PP_STATUS, IDC_EDIT_CAM_CENTER_CAL_UNLOAD_TRAY_PP_STATUS,
	IDC_EDIT_CAM_CENTER_CAL_LOAD_TEST_PP_1_STATUS, IDC_EDIT_CAM_CENTER_CAL_UNLOAD_TEST_PP_1_STATUS,
	IDC_EDIT_CAM_CENTER_CAL_LOAD_TEST_PP_2_STATUS, IDC_EDIT_CAM_CENTER_CAL_UNLOAD_TEST_PP_2_STATUS
};

static int m2_nCamStatus[VAT_HAND_MAX] = {
	IDC_CAM_CENTER_LOWERCAM_STATUS_1,		//LD Tray Pp
	IDC_CAM_CENTER_LOWERCAM_STATUS_2,		//UD Tray Pp
	IDC_CAM_CENTER_LOWERCAM_STATUS_3,		//LD Test Pp#1
	IDC_CAM_CENTER_LOWERCAM_STATUS_3,		//UD Test Pp#1
	IDC_CAM_CENTER_LOWERCAM_STATUS_4,		//LD Test Pp#2
	IDC_CAM_CENTER_LOWERCAM_STATUS_4,		//UD Test Pp#2
};


static int m2_nProgress[VAT_HAND_MAX] = {
	IDC_CAM_CENTER_PROGRESS_1, IDC_CAM_CENTER_PROGRESS_2, IDC_CAM_CENTER_PROGRESS_3, 
	IDC_CAM_CENTER_PROGRESS_4, IDC_CAM_CENTER_PROGRESS_5, IDC_CAM_CENTER_PROGRESS_6,
};

static int m2_nPercent[VAT_HAND_MAX] = {
	CG_IDC_CAM_CENTER_PROGRESS_PERCENT_1, CG_IDC_CAM_CENTER_PROGRESS_PERCENT_2, CG_IDC_CAM_CENTER_PROGRESS_PERCENT_3,
	CG_IDC_CAM_CENTER_PROGRESS_PERCENT_4, CG_IDC_CAM_CENTER_PROGRESS_PERCENT_5, CG_IDC_CAM_CENTER_PROGRESS_PERCENT_6,
};

static int m2_nRectGraphicView[VAT_HAND_MAX] = {
	IDC_STATIC_REAL_TIME_OFFSET_1, 
	IDC_STATIC_REAL_TIME_OFFSET_2,
	IDC_STATIC_REAL_TIME_OFFSET_3,
	IDC_STATIC_REAL_TIME_OFFSET_3,
	IDC_STATIC_REAL_TIME_OFFSET_4,
	IDC_STATIC_REAL_TIME_OFFSET_4
};

static int m2_nRectDataView[VAT_HAND_MAX][VAT_MAX_AXIS_XY] = {			
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X1, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y1 },		//LD Tray Pp													
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X2, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y2 },		//UD Tray Pp
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X3, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y3 },		//LD Test Pp#1
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X3, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y3 },		//UD Test Pp#1
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X4, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y4 },		//LD Test Pp#2
	{ IDC_STATIC_CAM_CENTER_OFFSET_DATA_X4, IDC_STATIC_CAM_CENTER_OFFSET_DATA_Y4 },		//UD Test Pp#2
};


//===================================================3. Picker Align(Mode3)
//[Measure Tab]
static int m3_nCamStatus[VAT_HAND_MAX] = {
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_1,		//LD Tray Pp
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_2,		//UD Tray Pp
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_3,		//LD Test Pp#1
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_4,		//UD Test Pp#1
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_5,		//LD Test Pp#2
	IDC_PICKER_ALIGN_LOWERCAM_STATUS_6		//UD Test Pp#2	
};

static int m3_nProgress[VAT_HAND_MAX] = {
	IDC_PICKER_ALIGN_PROGRESS_1, IDC_PICKER_ALIGN_PROGRESS_2, IDC_PICKER_ALIGN_PROGRESS_3,
	IDC_PICKER_ALIGN_PROGRESS_4, IDC_PICKER_ALIGN_PROGRESS_5, IDC_PICKER_ALIGN_PROGRESS_6,
};

static int m3_nPercent[VAT_HAND_MAX] = {
	CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_1, CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_2, CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_3,
	CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_4, CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_5, CG_IDC_PICKER_ALIGN_PROGRESS_PERCENT_6,
};

static int m3_nRectGraphicView_MeasureTab[VAT_HAND_MAX] = {
	IDC_STATIC_LOAD_TRAY_PP_OFFSET_MEASURE,
	IDC_STATIC_UNLOAD_TRAY_PP_OFFSET_MEASURE,
	IDC_STATIC_LOAD_TEST_PP_1_OFFSET_MEASURE,
	IDC_STATIC_UNLOAD_TEST_PP_1_OFFSET_MEASURE,
	IDC_STATIC_LOAD_TEST_PP_2_OFFSET_MEASURE,
	IDC_STATIC_UNLOAD_TEST_PP_2_OFFSET_MEASURE,
};


static int m3_nRectDataView_MeasureTab[VAT_HAND_MAX][VAT_MAX_AXIS_XY] = {
	{ IDC_STATIC_LD_TRAY_PP_OFFSET_DATA_X_MEASURE, IDC_STATIC_LD_TRAY_PP_OFFSET_DATA_Y_MEASURE },
	{ IDC_STATIC_UD_TRAY_PP_OFFSET_DATA_X_MEASURE, IDC_STATIC_UD_TRAY_PP_OFFSET_DATA_Y_MEASURE },
	{ IDC_STATIC_LD_TEST_PP_1_OFFSET_DATA_X_MEASURE, IDC_STATIC_LD_TEST_PP_1_OFFSET_DATA_Y_MEASURE },
	{ IDC_STATIC_UD_TEST_PP_1_OFFSET_DATA_X_MEASURE, IDC_STATIC_UD_TEST_PP_1_OFFSET_DATA_Y_MEASURE },
	{ IDC_STATIC_LD_TEST_PP_2_OFFSET_DATA_X_MEASURE, IDC_STATIC_LD_TEST_PP_2_OFFSET_DATA_Y_MEASURE },
	{ IDC_STATIC_UD_TEST_PP_2_OFFSET_DATA_X_MEASURE, IDC_STATIC_UD_TEST_PP_2_OFFSET_DATA_Y_MEASURE }
};


static int m3_nPitchStatus[VAT_HAND_MAX][VAT_PITCH_TYPE_MAX] = {
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_1, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_1 },
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_2, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_2 },
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_3, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_3 },
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_4, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_4 },
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_5, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_5 },
	{ IDC_EDIT_PICKER_ALIGN_WIDE_STATUS_6, IDC_EDIT_PICKER_ALIGN_NARROW_STATUS_6 }
};


//[Setting Tab]
static int m3_nEachPkr_TargetPos[VAT_HAND_MAX] = {
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_1, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_2,
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_3, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_4,
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_5, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB1_6
};

static int m3_nEachPkr_PrePos[VAT_HAND_MAX] = {
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_1, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_2,
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_3, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_4,
	IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_5, IDC_PICKER_ALIGN_SETTING_SPREAD_SUB2_6
};

static int m3_nMoveTargetPos[VAT_HAND_MAX] = {
	IDC_BTN_SELECTED_PKR_MOVE_1, IDC_BTN_SELECTED_PKR_MOVE_2,
	IDC_BTN_SELECTED_PKR_MOVE_3, IDC_BTN_SELECTED_PKR_MOVE_4,
	IDC_BTN_SELECTED_PKR_MOVE_5, IDC_BTN_SELECTED_PKR_MOVE_6
};

static int m3_nMovePrePos[VAT_HAND_MAX] = {
	IDC_BTN_SELECTED_PKR_PRE_MOVE_1, IDC_BTN_SELECTED_PKR_PRE_MOVE_2,
	IDC_BTN_SELECTED_PKR_PRE_MOVE_3, IDC_BTN_SELECTED_PKR_PRE_MOVE_4,
	IDC_BTN_SELECTED_PKR_PRE_MOVE_5, IDC_BTN_SELECTED_PKR_PRE_MOVE_6
};

static int m3_nEncoderRead[VAT_HAND_MAX] = {
	IDC_BTN_SELECTED_PKR_READ_ENCODER_1, IDC_BTN_SELECTED_PKR_READ_ENCODER_2,
	IDC_BTN_SELECTED_PKR_READ_ENCODER_3, IDC_BTN_SELECTED_PKR_READ_ENCODER_4,
	IDC_BTN_SELECTED_PKR_READ_ENCODER_5, IDC_BTN_SELECTED_PKR_READ_ENCODER_6
};

static int m3_nEncoderSave[VAT_HAND_MAX] = {
	IDC_BTN_SELECTED_PKR_SAVE_ENCODER_1, IDC_BTN_SELECTED_PKR_SAVE_ENCODER_2,
	IDC_BTN_SELECTED_PKR_SAVE_ENCODER_3, IDC_BTN_SELECTED_PKR_SAVE_ENCODER_4,
	IDC_BTN_SELECTED_PKR_SAVE_ENCODER_5, IDC_BTN_SELECTED_PKR_SAVE_ENCODER_6
};


static int m3_nRectGraphicView_SettingTab[VAT_HAND_MAX] = {
	IDC_STATIC_PICKER_ALIGN_SETTING_1,
	IDC_STATIC_PICKER_ALIGN_SETTING_2,
	IDC_STATIC_PICKER_ALIGN_SETTING_3,
	IDC_STATIC_PICKER_ALIGN_SETTING_4,
	IDC_STATIC_PICKER_ALIGN_SETTING_5,
	IDC_STATIC_PICKER_ALIGN_SETTING_6,
};


static int m3_nRectDataView_SettingTab[VAT_HAND_MAX][VAT_MAX_AXIS_XY] = {
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X1, IDC_STATIC_PICKER_ALIGN_SETTING_Y1 },
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X2, IDC_STATIC_PICKER_ALIGN_SETTING_Y2 },
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X3, IDC_STATIC_PICKER_ALIGN_SETTING_Y3 },
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X4, IDC_STATIC_PICKER_ALIGN_SETTING_Y4 },
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X5, IDC_STATIC_PICKER_ALIGN_SETTING_Y5 },
	{ IDC_STATIC_PICKER_ALIGN_SETTING_X6, IDC_STATIC_PICKER_ALIGN_SETTING_Y6 }
};


static int m3_nVisionLive[VAT_HAND_MAX] = {
	IDC_BTN_SELECTED_VISION_LIVE_1, IDC_BTN_SELECTED_VISION_LIVE_2,
	IDC_BTN_SELECTED_VISION_LIVE_3, IDC_BTN_SELECTED_VISION_LIVE_4,
	IDC_BTN_SELECTED_VISION_LIVE_5, IDC_BTN_SELECTED_VISION_LIVE_6
};


//[Sub][Picker Align Info]
static int m3_nRectGraphicView_Sub[VAT_HAND_MAX][VAT_DATA_INFO_TYPE_MAX]
{
	{ IDC_STATIC_LOAD_TRAY_PP_WIDE, IDC_STATIC_LOAD_TRAY_PP_NARROW, IDC_STATIC_LOAD_TRAY_PP_W_TO_N },
	{ IDC_STATIC_UNLOAD_TRAY_PP_WIDE, IDC_STATIC_UNLOAD_TRAY_PP_NARROW, IDC_STATIC_UNLOAD_TRAY_PP_W_TO_N },
	{ IDC_STATIC_LOAD_TEST_PP_1_WIDE, IDC_STATIC_LOAD_TEST_PP_1_NARROW, IDC_STATIC_LOAD_TEST_PP_1_W_TO_N },
	{ IDC_STATIC_UNLOAD_TEST_PP_1_WIDE, IDC_STATIC_UNLOAD_TEST_PP_1_NARROW, IDC_STATIC_UNLOAD_TEST_PP_1_W_TO_N },
	{ IDC_STATIC_LOAD_TEST_PP_2_WIDE, IDC_STATIC_LOAD_TEST_PP_2_NARROW, IDC_STATIC_LOAD_TEST_PP_2_W_TO_N },
	{ IDC_STATIC_UNLOAD_TEST_PP_2_WIDE, IDC_STATIC_UNLOAD_TEST_PP_2_NARROW, IDC_STATIC_UNLOAD_TEST_PP_2_W_TO_N },
};

static int m3_nHandPanel_Sub[VAT_HAND_MAX][VAT_DATA_INFO_TYPE_MAX] = {
	{ IDC_SSPANEL_LD_TRAYPP_WIDE,	IDC_SSPANEL_LD_TRAYPP_NARROW,	IDC_SSPANEL_LD_TRAYPP_W_TO_N },
	{ IDC_SSPANEL_UD_TRAYPP_WIDE,	IDC_SSPANEL_UD_TRAYPP_NARROW,	IDC_SSPANEL_UD_TRAYPP_W_TO_N },
	{ IDC_SSPANEL_LD_TESTPP_1_WIDE, IDC_SSPANEL_LD_TESTPP_1_NARROW, IDC_SSPANEL_LD_TESTPP_1_W_TO_N },
	{ IDC_SSPANEL_UD_TESTPP_1_WIDE, IDC_SSPANEL_UD_TESTPP_1_NARROW, IDC_SSPANEL_UD_TESTPP_1_W_TO_N },
	{ IDC_SSPANEL_LD_TESTPP_2_WIDE, IDC_SSPANEL_LD_TESTPP_2_NARROW, IDC_SSPANEL_LD_TESTPP_2_W_TO_N },
	{ IDC_SSPANEL_UD_TESTPP_2_WIDE, IDC_SSPANEL_UD_TESTPP_2_NARROW, IDC_SSPANEL_UD_TESTPP_2_W_TO_N },
};


//===================================================4. Vision Auto Teaching(Mode4)
static int m4_nRectGraphicView[VAT_HAND_MAX] = {
	IDC_STATIC_VAT_GRAPHIC_OFFSET_1,
	IDC_STATIC_VAT_GRAPHIC_OFFSET_2,
	IDC_STATIC_VAT_GRAPHIC_OFFSET_3,
	IDC_STATIC_VAT_GRAPHIC_OFFSET_4,
	IDC_STATIC_VAT_GRAPHIC_OFFSET_5,
	IDC_STATIC_VAT_GRAPHIC_OFFSET_6,
};


static int m4_nRectDataView[VAT_HAND_MAX][VAT_MAX_AXIS_XY] = {
	{ IDC_STATIC_VAT_OFFSET_DATA_X1, IDC_STATIC_VAT_OFFSET_DATA_Y1 },
	{ IDC_STATIC_VAT_OFFSET_DATA_X2, IDC_STATIC_VAT_OFFSET_DATA_Y2 },
	{ IDC_STATIC_VAT_OFFSET_DATA_X3, IDC_STATIC_VAT_OFFSET_DATA_Y3 },
	{ IDC_STATIC_VAT_OFFSET_DATA_X4, IDC_STATIC_VAT_OFFSET_DATA_Y4 },
	{ IDC_STATIC_VAT_OFFSET_DATA_X5, IDC_STATIC_VAT_OFFSET_DATA_Y5 },
	{ IDC_STATIC_VAT_OFFSET_DATA_X6, IDC_STATIC_VAT_OFFSET_DATA_Y6 }
};


static int m4_nOptHandOnly[VAT_HAND_MAX] = {
	IDC_SSPANEL_VAT_HAND_ONLY_1, 
	IDC_SSPANEL_VAT_HAND_ONLY_2,
	IDC_SSPANEL_VAT_HAND_ONLY_3, 
	_VAT_ID_SPARE,
	IDC_SSPANEL_VAT_HAND_ONLY_4,
	_VAT_ID_SPARE,
};


static int m4_nOptUnitOnly[VAT_HAND_MAX] = {
	IDC_SSPANEL_VAT_UNIT_ONLY_1, 
	IDC_SSPANEL_VAT_UNIT_ONLY_2,
	IDC_SSPANEL_VAT_UNIT_ONLY_3, 
	_VAT_ID_SPARE,
	IDC_SSPANEL_VAT_UNIT_ONLY_4,
	_VAT_ID_SPARE,
};


static int m4_nPartPos_LDTrayPp[VAT_MAX_TRAY_PP_LOC_COUNT] = {
	_VAT_ID_SPARE,								//Tbl1
	IDC_EDIT_VAT_LD_TRAY_PP_STATUS1,			//Tbl2
	IDC_EDIT_VAT_LD_TRAY_PP_STATUS2,			//Tbl3
	_VAT_ID_SPARE,								//Tbl4
	_VAT_ID_SPARE,								//Conv1
	_VAT_ID_SPARE,								//Conv2
	_VAT_ID_SPARE,								//Conv3
	_VAT_ID_SPARE,								//Conv4
	_VAT_ID_SPARE,								//Conv5
	_VAT_ID_SPARE,								//Conv6
	_VAT_ID_SPARE,								//Conv7
	IDC_EDIT_VAT_LD_TRAY_PP_STATUS3,			//Feeder
};

static int m4_nPartPos_UDTrayPp[VAT_MAX_TRAY_PP_LOC_COUNT] = {
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS1,			//Tbl1
	_VAT_ID_SPARE,								//Tbl2
	_VAT_ID_SPARE,								//Tbl3
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS2,			//Tbl4
	_VAT_ID_SPARE,								//Conv1
	_VAT_ID_SPARE,								//Conv2
	_VAT_ID_SPARE,								//Conv3
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS3,			//Conv4
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS4,			//Conv5
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS5,			//Conv6
	IDC_EDIT_VAT_UD_TRAY_PP_STATUS6,			//Conv7
	_VAT_ID_SPARE,								//Feeder
};

static int m4_nPartPos_LDTestPp1[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS1,			//Station1
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS2,			//Station2
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS3,			//Station3
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS4,			//Station4
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS5,			//LD Tbl1
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS6,			//LD Tbl2
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS7,			//LD Tbl3
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS8,			//LD Tbl4
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS9,			//UD Tbl1
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS10,			//UD Tbl2
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS11,			//UD Tbl3
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS12,			//UD Tbl4
	IDC_EDIT_VAT_LD_TEST_PP1_STATUS13,			//Clean Tbl
};

static int m4_nPartPos_UDTestPp1[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS1,			//Station1
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS2,			//Station2
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS3,			//Station3
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS4,			//Station4
	_VAT_ID_SPARE,								//LD Tbl1
	_VAT_ID_SPARE,								//LD Tbl2
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS5,			//LD Tbl3
	_VAT_ID_SPARE,								//LD Tbl4
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS6,			//UD Tbl1
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS7,			//UD Tbl2
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS8,			//UD Tbl3
	IDC_EDIT_VAT_UD_TEST_PP1_STATUS9,			//UD Tbl4
	_VAT_ID_SPARE,								//Clean Tbl
};

static int m4_nPartPos_LDTestPp2[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS1,			//Station1
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS2,			//Station2
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS3,			//Station3
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS4,			//Station4
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS5,			//LD Tbl1
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS6,			//LD Tbl2
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS7,			//LD Tbl3
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS8,			//LD Tbl4
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS9,			//UD Tbl1
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS10,			//UD Tbl2
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS11,			//UD Tbl3
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS12,			//UD Tbl4
	IDC_EDIT_VAT_LD_TEST_PP2_STATUS13,			//Clean Tbl
};

static int m4_nPartPos_UDTestPp2[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS1,			//Station1
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS2,			//Station2
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS3,			//Station3
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS4,			//Station4
	_VAT_ID_SPARE,								//LD Tbl1
	_VAT_ID_SPARE,								//LD Tbl2
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS5,			//LD Tbl3
	_VAT_ID_SPARE,								//LD Tbl4
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS6,			//UD Tbl1
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS7,			//UD Tbl2
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS8,			//UD Tbl3
	IDC_EDIT_VAT_UD_TEST_PP2_STATUS9,			//UD Tbl4
	_VAT_ID_SPARE,								//Clean Tbl
};

//vision Target Overview
static int m4_nTargetOverviewIdx_TrayPp[VAT_MAX_TRAY_PP_LOC_COUNT] = {
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_1,	 //Tbl1
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_2,	 //Tbl2
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_3,	 //Tbl3
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_4,	 //Tbl4
	_VAT_ID_SPARE,						 //Conv1
	_VAT_ID_SPARE,						 //Conv2
	_VAT_ID_SPARE,						 //Conv3
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_5,	 //Conv4
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_6,	 //Conv5
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_7,	 //Conv6
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_8,	 //Conv7
	IDC_VAT_TARGET_OVERVIEW_TRAY_PP_9,	 //Feeder
};

static int m4_nTargetOverviewIdx_TestPp1[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_1,		//Station1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_2,		//Station2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_3,		//Station3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_4,		//Station4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_5,		//LD Tbl1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_6,		//LD Tbl2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_7,		//LD Tbl3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_8,		//LD Tbl4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_9,		//UD Tbl1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_10,	//UD Tbl2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_11,	//UD Tbl3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_12,	//UD Tbl4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP1_13,	//Clean Tbl
};

static int m4_nTargetOverviewIdx_TestPp2[VAT_MAX_TEST_PP_LOC_COUNT] = {
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_1,		//Station1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_2,		//Station2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_3,		//Station3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_4,		//Station4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_5,		//LD Tbl1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_6,		//LD Tbl2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_7,		//LD Tbl3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_8,		//LD Tbl4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_9,		//UD Tbl1
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_10,	//UD Tbl2
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_11,	//UD Tbl3
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_12,	//UD Tbl4
	IDC_VAT_TARGET_OVERVIEW_TEST_PP2_13,	//Clean Tbl
};

// static int m4_nYCheckListPosition[VAT_HAND_MAX] = {
// 	_VAT_ID_SPARE, _VAT_ID_SPARE,
// 	IDC_EDIT_CAM_CENTER_CAL_LOAD_TEST_PP_1_STATUS, IDC_EDIT_CAM_CENTER_CAL_UNLOAD_TEST_PP_1_STATUS,
// 	IDC_EDIT_CAM_CENTER_CAL_LOAD_TEST_PP_2_STATUS, IDC_EDIT_CAM_CENTER_CAL_UNLOAD_TEST_PP_2_STATUS
// };

//===================================================4. Z Auto Teaching(Mode4)
//Picker Current Positoin ID
static int m4_nCurPosStaticIdx[VAT_HAND_MAX][VAT_PICKER_MAX] = {
	{ IDC_LD_TRAYPP_POS_1, IDC_LD_TRAYPP_POS_2, IDC_LD_TRAYPP_POS_3, IDC_LD_TRAYPP_POS_4, IDC_LD_TRAYPP_POS_5, IDC_LD_TRAYPP_POS_6, IDC_LD_TRAYPP_POS_7, IDC_LD_TRAYPP_POS_8 },
	{ IDC_UD_TRAYPP_POS_1, IDC_UD_TRAYPP_POS_2, IDC_UD_TRAYPP_POS_3, IDC_UD_TRAYPP_POS_4, IDC_UD_TRAYPP_POS_5, IDC_UD_TRAYPP_POS_6, IDC_UD_TRAYPP_POS_7, IDC_UD_TRAYPP_POS_8 },
	{ IDC_LD_TESTPP_1_POS_1, IDC_LD_TESTPP_1_POS_2, IDC_LD_TESTPP_1_POS_3, IDC_LD_TESTPP_1_POS_4, IDC_LD_TESTPP_1_POS_5, IDC_LD_TESTPP_1_POS_6, IDC_LD_TESTPP_1_POS_7, IDC_LD_TESTPP_1_POS_8 },
	{ IDC_UD_TESTPP_1_POS_1, IDC_UD_TESTPP_1_POS_2, IDC_UD_TESTPP_1_POS_3, IDC_UD_TESTPP_1_POS_4, IDC_UD_TESTPP_1_POS_5, IDC_UD_TESTPP_1_POS_6, IDC_UD_TESTPP_1_POS_7, IDC_UD_TESTPP_1_POS_8, },
	{ IDC_LD_TESTPP_2_POS_1, IDC_LD_TESTPP_2_POS_2, IDC_LD_TESTPP_2_POS_3, IDC_LD_TESTPP_2_POS_4, IDC_LD_TESTPP_2_POS_5, IDC_LD_TESTPP_2_POS_6, IDC_LD_TESTPP_2_POS_7, IDC_LD_TESTPP_2_POS_8 },
	{ IDC_UD_TESTPP_2_POS_1, IDC_UD_TESTPP_2_POS_2, IDC_UD_TESTPP_2_POS_3, IDC_UD_TESTPP_2_POS_4, IDC_UD_TESTPP_2_POS_5, IDC_UD_TESTPP_2_POS_6, IDC_UD_TESTPP_2_POS_7, IDC_UD_TESTPP_2_POS_8, },
};

//Picker Vacuum ID
static int m4_nVacStaticIdx[VAT_HAND_MAX][VAT_PICKER_MAX] = {
	{ IDC_LD_TRAYPP_VAC_1, IDC_LD_TRAYPP_VAC_2, IDC_LD_TRAYPP_VAC_3, IDC_LD_TRAYPP_VAC_4, IDC_LD_TRAYPP_VAC_5, IDC_LD_TRAYPP_VAC_6, IDC_LD_TRAYPP_VAC_7, IDC_LD_TRAYPP_VAC_8 },
	{ IDC_UD_TRAYPP_VAC_1, IDC_UD_TRAYPP_VAC_2, IDC_UD_TRAYPP_VAC_3, IDC_UD_TRAYPP_VAC_4, IDC_UD_TRAYPP_VAC_5, IDC_UD_TRAYPP_VAC_6, IDC_UD_TRAYPP_VAC_7, IDC_UD_TRAYPP_VAC_8 },
	{ IDC_LD_TESTPP_1_VAC_1, IDC_LD_TESTPP_1_VAC_2, IDC_LD_TESTPP_1_VAC_3, IDC_LD_TESTPP_1_VAC_4, IDC_LD_TESTPP_1_VAC_5, IDC_LD_TESTPP_1_VAC_6, IDC_LD_TESTPP_1_VAC_7, IDC_LD_TESTPP_1_VAC_8 },
	{ IDC_UD_TESTPP_1_VAC_1, IDC_UD_TESTPP_1_VAC_2, IDC_UD_TESTPP_1_VAC_3, IDC_UD_TESTPP_1_VAC_4, IDC_UD_TESTPP_1_VAC_5, IDC_UD_TESTPP_1_VAC_6, IDC_UD_TESTPP_1_VAC_7, IDC_UD_TESTPP_1_VAC_8, },
	{ IDC_LD_TESTPP_2_VAC_1, IDC_LD_TESTPP_2_VAC_2, IDC_LD_TESTPP_2_VAC_3, IDC_LD_TESTPP_2_VAC_4, IDC_LD_TESTPP_2_VAC_5, IDC_LD_TESTPP_2_VAC_6, IDC_LD_TESTPP_2_VAC_7, IDC_LD_TESTPP_2_VAC_8 },
	{ IDC_UD_TESTPP_2_VAC_1, IDC_UD_TESTPP_2_VAC_2, IDC_UD_TESTPP_2_VAC_3, IDC_UD_TESTPP_2_VAC_4, IDC_UD_TESTPP_2_VAC_5, IDC_UD_TESTPP_2_VAC_6, IDC_UD_TESTPP_2_VAC_7, IDC_UD_TESTPP_2_VAC_8, },
};

//Picker Data Display ID
static int m4_nDataStaticIdx[VAT_HAND_MAX][VAT_PICKER_MAX] = {
	{ IDC_LD_TRAYPP_DATA_1, IDC_LD_TRAYPP_DATA_2, IDC_LD_TRAYPP_DATA_3, IDC_LD_TRAYPP_DATA_4, IDC_LD_TRAYPP_DATA_5, IDC_LD_TRAYPP_DATA_6, IDC_LD_TRAYPP_DATA_7, IDC_LD_TRAYPP_DATA_8 },
	{ IDC_UD_TRAYPP_DATA_1, IDC_UD_TRAYPP_DATA_2, IDC_UD_TRAYPP_DATA_3, IDC_UD_TRAYPP_DATA_4, IDC_UD_TRAYPP_DATA_5, IDC_UD_TRAYPP_DATA_6, IDC_UD_TRAYPP_DATA_7, IDC_UD_TRAYPP_DATA_8 },
	{ IDC_LD_TESTPP_1_DATA_1, IDC_LD_TESTPP_1_DATA_2, IDC_LD_TESTPP_1_DATA_3, IDC_LD_TESTPP_1_DATA_4, IDC_LD_TESTPP_1_DATA_5, IDC_LD_TESTPP_1_DATA_6, IDC_LD_TESTPP_1_DATA_7, IDC_LD_TESTPP_1_DATA_8 },
	{ IDC_UD_TESTPP_1_DATA_1, IDC_UD_TESTPP_1_DATA_2, IDC_UD_TESTPP_1_DATA_3, IDC_UD_TESTPP_1_DATA_4, IDC_UD_TESTPP_1_DATA_5, IDC_UD_TESTPP_1_DATA_6, IDC_UD_TESTPP_1_DATA_7, IDC_UD_TESTPP_1_DATA_8, },
	{ IDC_LD_TESTPP_2_DATA_1, IDC_LD_TESTPP_2_DATA_2, IDC_LD_TESTPP_2_DATA_3, IDC_LD_TESTPP_2_DATA_4, IDC_LD_TESTPP_2_DATA_5, IDC_LD_TESTPP_2_DATA_6, IDC_LD_TESTPP_2_DATA_7, IDC_LD_TESTPP_2_DATA_8 },
	{ IDC_UD_TESTPP_2_DATA_1, IDC_UD_TESTPP_2_DATA_2, IDC_UD_TESTPP_2_DATA_3, IDC_UD_TESTPP_2_DATA_4, IDC_UD_TESTPP_2_DATA_5, IDC_UD_TESTPP_2_DATA_6, IDC_UD_TESTPP_2_DATA_7, IDC_UD_TESTPP_2_DATA_8, },
};

//Offset Data Panel
static int m4_nDataPanelIdx[VAT_HAND_MAX][_VAT_DATA_TYPE_MAX] = {
	{ IDC_SSPANEL_LD_TRAYPP_FLATNESS_OFFSET, IDC_SSPANEL_LD_TRAYPP_PICK_POS },
	{ IDC_SSPANEL_UD_TRAYPP_FLATNESS_OFFSET, IDC_SSPANEL_UD_TRAYPP_PICK_POS },
	{ IDC_SSPANEL_LD_TESTPP_1_FLATNESS_OFFSET, IDC_SSPANEL_LD_TESTPP_1_PICK_POS },
	{ IDC_SSPANEL_UD_TESTPP_1_FLATNESS_OFFSET, IDC_SSPANEL_UD_TESTPP_1_PICK_POS },
	{ IDC_SSPANEL_LD_TESTPP_2_FLATNESS_OFFSET, IDC_SSPANEL_LD_TESTPP_2_PICK_POS },
	{ IDC_SSPANEL_UD_TESTPP_2_FLATNESS_OFFSET, IDC_SSPANEL_UD_TESTPP_2_PICK_POS },
};

// Design Value
 static int m4_nDesignValue[VAT_MAX_DESIGN_VALUE_Z_AUTO_TEACHING] = {
	 IDC_EDIT_TBL_HEIGHT, 
	 IDC_EDIT_TBL_POCKET_Z, 

	 IDC_EDIT_CLEAN_TBL_HEIGHT, 
	 IDC_EDIT_CLEAN_TBL_POCKET_Z,

	 IDC_EDIT_C_TRAY_HEIGHT, 
	 IDC_EDIT_C_TRAY_POCKET_Z,

	 IDC_EDIT_STATION_HEIGHT, 
	 IDC_EDIT_STATION_SOCKET_Z,

	 IDC_EDIT_C_TRAY_JIG_HEIGHT, 
	 IDC_EDIT_DEVICE_HEIGHT,
 };


//#define PICKER_DATA_ON_SETFOCUS		//


