copy .\Release\LIB_MC.dll ..\..\..\..\Bin
copy .\Release\LIB_MC.pdb ..\..\..\..\Bin
copy .\Release\LIB_MC.lib ..\..\..\LibFiles
copy DEF_MOTION.h ..\..\..\Include
copy Motion_Cont.h ..\..\..\Include
copy OneAxis.h ..\..\..\Include
copy TESTER_IF_Cont.h ..\..\..\Include
copy DEF_LIB_TESTER_IF.h ..\..\..\Include
copy DIO_Cont.h ..\..\..\Include
copy AIO_Cont.h ..\..\..\Include
copy TIFWnd.h ..\..\..\Include