@echo off
setlocal enabledelayedexpansion

:: 배치 파일이 위치한 폴더를 원본 폴더 경로로 설정합니다.
set "sourcepath=%~dp0"

:: 대상 폴더 경로를 설정합니다. 필요에 따라 변경 및 추가할 수 있습니다.
set "targetpath1=%~dp0../Debug1"
set "targetpath2=%~dp0../Debug2"
set "targetpath3=%~dp0../Debug3"
set "targetpath4=%~dp0../Debug4"
set "targetpath5=%~dp0../Debug5"
set "targetpath6=%~dp0../Debug6"
set "targetpath7=%~dp0../Debug7"
set "targetpath8=%~dp0../Debug8"
set "targetpath9=%~dp0../Debug9"
set "targetpath10=%~dp0../Debug10"
set "targetpath11=%~dp0../Debug11"
set "targetpath12=%~dp0../Debug12"
set "targetpath13=%~dp0../Debug13"
set "targetpath14=%~dp0../Debug14"
set "targetpath15=%~dp0../Debug15"
set "targetpath16=%~dp0../Debug16"
set "targetpath17=%~dp0../Debug17"
set "targetpath18=%~dp0../Debug18"
set "targetpath19=%~dp0../Debug19"
set "targetpath20=%~dp0../Debug20"
set "targetpath21=%~dp0../Debug21"
set "targetpath22=%~dp0../Debug22"
set "targetpath23=%~dp0../Debug23"
set "targetpath24=%~dp0../Debug24"
set "targetpath25=%~dp0../Debug25"
set "targetpath26=%~dp0../Debug26"
set "targetpath27=%~dp0../Debug27"
set "targetpath28=%~dp0../Debug28"
set "targetpath29=%~dp0../Debug29"
set "targetpath30=%~dp0../Debug30"
set "targetpath31=%~dp0../Debug31"
set "targetpath32=%~dp0../Debug32"
set "targetpath33=%~dp0../Debug33"
set "targetpath34=%~dp0../Debug34"
set "targetpath35=%~dp0../Debug35"
set "targetpath36=%~dp0../Debug36"
set "targetpath37=%~dp0../Debug37"
set "targetpath38=%~dp0../Debug38"
set "targetpath39=%~dp0../Debug39"
set "targetpath40=%~dp0../Debug40"
set "targetpath41=%~dp0../Debug41"
set "targetpath42=%~dp0../Debug42"
set "targetpath43=%~dp0../Debug43"
set "targetpath44=%~dp0../Debug44"
set "targetpath45=%~dp0../Debug45"
set "targetpath46=%~dp0../Debug46"
set "targetpath47=%~dp0../Debug47"
set "targetpath48=%~dp0../Debug48"
set "targetpath49=%~dp0../Debug49"
set "targetpath50=%~dp0../Debug50"
set "targetpath51=%~dp0../Debug51"
set "targetpath52=%~dp0../Debug52"
set "targetpath53=%~dp0../Debug53"
set "targetpath54=%~dp0../Debug54"
set "targetpath55=%~dp0../Debug55"
set "targetpath56=%~dp0../Debug56"
set "targetpath57=%~dp0../Debug57"
set "targetpath58=%~dp0../Debug58"
set "targetpath59=%~dp0../Debug59"
set "targetpath60=%~dp0../Debug60"
set "targetpath61=%~dp0../Debug61"
set "targetpath62=%~dp0../Debug62"
set "targetpath63=%~dp0../Debug63"
set "targetpath64=%~dp0../Debug64"

:: 제외할 파일 이름을 설정합니다. 필요에 따라 변경할 수 있습니다.
set "excludefilename=Setting.ini"

if not exist !targetpath1! (
			mkdir "!targetpath1!"
			mkdir "!targetpath2!"
			mkdir "!targetpath3!"
			mkdir "!targetpath4!"
			mkdir "!targetpath5!"
			mkdir "!targetpath6!"
			mkdir "!targetpath7!"
			mkdir "!targetpath8!"
			mkdir "!targetpath9!"
			mkdir "!targetpath10!"
			mkdir "!targetpath11!"
			mkdir "!targetpath12!"
			mkdir "!targetpath13!"
			mkdir "!targetpath14!"
			mkdir "!targetpath15!"
			mkdir "!targetpath16!"
			mkdir "!targetpath17!"
			mkdir "!targetpath18!"
			mkdir "!targetpath19!"
			mkdir "!targetpath20!"
			mkdir "!targetpath21!"
			mkdir "!targetpath22!"
			mkdir "!targetpath23!"
			mkdir "!targetpath24!"
			mkdir "!targetpath25!"
			mkdir "!targetpath26!"
			mkdir "!targetpath27!"
			mkdir "!targetpath28!"
			mkdir "!targetpath29!"
			mkdir "!targetpath30!"
			mkdir "!targetpath31!"
			mkdir "!targetpath32!"
			mkdir "!targetpath33!"
			mkdir "!targetpath34!"
			mkdir "!targetpath35!"
			mkdir "!targetpath36!"
			mkdir "!targetpath37!"
			mkdir "!targetpath38!"
			mkdir "!targetpath39!"
			mkdir "!targetpath40!"
			mkdir "!targetpath41!"
			mkdir "!targetpath42!"
			mkdir "!targetpath43!"
			mkdir "!targetpath44!"
			mkdir "!targetpath45!"
			mkdir "!targetpath46!"
			mkdir "!targetpath47!"
			mkdir "!targetpath48!"
			mkdir "!targetpath49!"
			mkdir "!targetpath50!"
			mkdir "!targetpath51!"
			mkdir "!targetpath52!"
			mkdir "!targetpath53!"
			mkdir "!targetpath54!"
			mkdir "!targetpath55!"
			mkdir "!targetpath56!"
			mkdir "!targetpath57!"
			mkdir "!targetpath58!"
			mkdir "!targetpath59!"
			mkdir "!targetpath60!"
			mkdir "!targetpath61!"
			mkdir "!targetpath62!"
			mkdir "!targetpath63!"
			mkdir "!targetpath64!"	
		)   

for %%I in ("%sourcepath%\*") do (
    if /i "%%~nxI" neq "!excludefilename!" (
		
        copy "%%I" "!targetpath1!\"
        copy "%%I" "!targetpath2!\"
		copy "%%I" "!targetpath3!\"
        copy "%%I" "!targetpath4!\"
	    copy "%%I" "!targetpath5!\"
        copy "%%I" "!targetpath6!\"
		copy "%%I" "!targetpath7!\"
        copy "%%I" "!targetpath8!\"
        copy "%%I" "!targetpath9!\"
        copy "%%I" "!targetpath10!\"
		copy "%%I" "!targetpath11!\"
        copy "%%I" "!targetpath12!\"
        copy "%%I" "!targetpath13!\"
        copy "%%I" "!targetpath14!\"
		copy "%%I" "!targetpath15!\"
        copy "%%I" "!targetpath16!\"
        copy "%%I" "!targetpath17!\"
        copy "%%I" "!targetpath18!\"
		copy "%%I" "!targetpath19!\"
        copy "%%I" "!targetpath20!\"
        copy "%%I" "!targetpath21!\"
        copy "%%I" "!targetpath22!\"
		copy "%%I" "!targetpath23!\"
        copy "%%I" "!targetpath24!\"
        copy "%%I" "!targetpath25!\"
        copy "%%I" "!targetpath26!\"
		copy "%%I" "!targetpath27!\"
        copy "%%I" "!targetpath28!\"
        copy "%%I" "!targetpath29!\"
        copy "%%I" "!targetpath30!\"
		copy "%%I" "!targetpath31!\"
        copy "%%I" "!targetpath32!\"
        copy "%%I" "!targetpath33!\"
        copy "%%I" "!targetpath34!\"
		copy "%%I" "!targetpath35!\"
        copy "%%I" "!targetpath36!\"
        copy "%%I" "!targetpath37!\"
        copy "%%I" "!targetpath38!\"
		copy "%%I" "!targetpath39!\"
        copy "%%I" "!targetpath40!\"
        copy "%%I" "!targetpath41!\"
        copy "%%I" "!targetpath42!\"
		copy "%%I" "!targetpath43!\"
        copy "%%I" "!targetpath44!\"
        copy "%%I" "!targetpath45!\"
        copy "%%I" "!targetpath46!\"
		copy "%%I" "!targetpath47!\"
        copy "%%I" "!targetpath48!\"
        copy "%%I" "!targetpath49!\"
        copy "%%I" "!targetpath50!\"
		copy "%%I" "!targetpath51!\"
        copy "%%I" "!targetpath52!\"
        copy "%%I" "!targetpath53!\"
        copy "%%I" "!targetpath54!\"
		copy "%%I" "!targetpath55!\"
        copy "%%I" "!targetpath56!\"
        copy "%%I" "!targetpath57!\"
        copy "%%I" "!targetpath58!\"
		copy "%%I" "!targetpath59!\"
        copy "%%I" "!targetpath60!\"
        copy "%%I" "!targetpath61!\"
        copy "%%I" "!targetpath62!\"
		copy "%%I" "!targetpath63!\"
        copy "%%I" "!targetpath64!\"		
    )
)

echo 파일을 복사했습니다.
exit