// DlgSimulDioSLT.cpp : 구현 파일입니다.
//

#include "stdafx.h"
#include "SLT_MC.h"
#include "DlgSimulDioSLT.h"
#include "afxdialogex.h"


// CDlgSimulDioSLT 대화 상자입니다.

IMPLEMENT_DYNAMIC(CDlgSimulDioSLT, CDialogEx)

CDlgSimulDioSLT::CDlgSimulDioSLT(CWnd* pParent /*=NULL*/)
	: CDialogEx(CDlgSimulDioSLT::IDD, pParent)
{

}

CDlgSimulDioSLT::~CDlgSimulDioSLT()
{
}

void CDlgSimulDioSLT::DoDataExchange(CDataExchange* pDX)
{
	CDialogEx::DoDataExchange(pDX);
}

void CDlgSimulDioSLT::SetSimulTimer_On(  LPARAM _lParam, int _DI_number1, int _DI_number2 )
{
	int nTID = ( _lParam == TRUE ) ? _DI_number1 : _DI_number2;
	SetTimer( nTID, 50, NULL );
}

void CDlgSimulDioSLT::SetSimul_IO_One_OnOff( int _IDEvent, int _DI_number, BOOL _On )
{
	KillTimer( _IDEvent );
	g_IO.SetSimulDi( _DI_number, _On );
}

void CDlgSimulDioSLT::SetSimul_IO_Two_OnOff( int _IDEvent, int _DI_number1, int _DI_number2, BOOL _On )
{
	KillTimer( _IDEvent );
	g_IO.SetSimulDi( _DI_number1, _On );
	g_IO.SetSimulDi( _DI_number2, !(_On) );
}


BEGIN_MESSAGE_MAP(CDlgSimulDioSLT, CDialogEx)
	ON_WM_DESTROY()
	ON_WM_SHOWWINDOW()
	ON_WM_TIMER()
	ON_MESSAGE(UM_DIO_SIM_DO_CHANGED, RcvChangedDo)
END_MESSAGE_MAP()


// CDlgSimulDioSLT 메시지 처리기입니다.


BOOL CDlgSimulDioSLT::PreTranslateMessage(MSG* pMsg)
{
	// TODO: 여기에 특수화된 코드를 추가 및/또는 기본 클래스를 호출합니다.

	return CDialogEx::PreTranslateMessage(pMsg);
}


BOOL CDlgSimulDioSLT::OnInitDialog()
{
	CDialogEx::OnInitDialog();

	// 이 다이얼로그는 시뮬레이션 모드 일 때만 생성이 된다.
	// 프로그램 시작 시에 simulation을 위해 켜줘야 하는 IO가 있다면 여기에서 켜줘라.

	for(int i=0; i < MAX_DI_COUNT; i++){
		//g_IO.SetSimulDi(i, DEF_OFF);
	}

	g_IO.SetSimulDi(DI_HINGED_LEFT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_FRONT_LEFT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_FRONT_RIGHT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_HINGED_RIGHT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_SLIDE_LEFT_F1_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_SLIDE_LEFT_R2_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_SLIDE_RIGHT_F1_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_SLIDE_RIGHT_R2_DOORLOCK_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_REAR_RIGHT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_REAR_LEFT_DOORLOCK_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_FRONT_LEFT2_DOORLOCK, DEF_ON);

	g_IO.SetSimulDi(DI_MIDDLE_LEFT_EMO_SW_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_MIDDLE_RIGHT_EMO_SW_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_REAR_LEFT_EMO_SW_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_FRONT_LEFT_EMO_SW_SEN  , DEF_ON);
	g_IO.SetSimulDi(DI_FRONT_RIGHT_EMO_SW_SEN , DEF_ON);
	g_IO.SetSimulDi(DI_REAR_RIGHT_EMO_SW_SEN, DEF_ON);
	
	g_IO.SetSimulDi(DI_MAIN_POWER_ON_SEN1, DEF_ON);
	g_IO.SetSimulDi(DI_MAIN_POWER_ON_SEN2, DEF_ON);
	g_IO.SetSimulDi(DI_SERVO_POWER_ON_SEN1, DEF_ON);

	g_IO.SetSimulDi(DI_POWER_BOX_CP_TRIP_ALARM_SEN, DEF_ON );
	g_IO.SetSimulDi(DI_LOAD_UNLOAD_TRANSFER_SERVO_CP_TRIP_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_TEST1_PRESS1_SERVO_CP_TRIP_ALARM_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_TABLE_SERVO_CP_TRIP_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_TEST2_PRESS2_CP_TRIP_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_AC_FAN_CP_TRIP_SEN, DEF_ON);

 	g_IO.SetSimulDi(DI_MAIN_AIR1_SEN, DEF_ON);
 	g_IO.SetSimulDi(DI_MAIN_AIR2_SEN, DEF_ON);
	
	g_IO.SetSimulDi(DI_IONIZER_1_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_2_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_3_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_4_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_5_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_6_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_7_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_IONIZER_8_ALARM, DEF_ON);
	
	g_IO.SetSimulDi(DI_PRESS1_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS2_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS3_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS4_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS5_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS6_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS7_IONIZER_ALARM, DEF_ON);
	g_IO.SetSimulDi(DI_PRESS8_IONIZER_ALARM, DEF_ON);
	
// 	g_IO.SetSimulDi( DI_LOAD_TABLE1_IONIZER_ALRAM_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_LOAD_TABLE1_IONIZER_FAN_ALRAM_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_LOAD_TABLE2_IONIZER_ALRAM_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_LOAD_TABLE2_IONIZER_FAN_ALRAM_SEN, DEF_ON);
// 
// 	g_IO.SetSimulDi( DI_STACKER1_IONIZER_ALRAM_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_STACKER1_IONIZER_FAN_ALRAM_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_STACKER3_IONIZER_ALRAM_SEN, DEF_ON );
// 	g_IO.SetSimulDi( DI_STACKER3_IONIZER_FAN_ALRAM_SEN, DEF_ON );
// 	g_IO.SetSimulDi( DI_STACKER5_IONIZER_ALRAM_SEN, DEF_ON );
// 	g_IO.SetSimulDi( DI_STACKER5_IONIZER_FAN_ALRAM_SEN, DEF_ON );
// 	g_IO.SetSimulDi( DI_STACKER7_IONIZER_ALRAM_SEN, DEF_ON );
// 	g_IO.SetSimulDi( DI_STACKER7_IONIZER_FAN_ALRAM_SEN, DEF_ON );
// 	
// 	g_IO.SetSimulDi(DI_LOAD_TABLE1_IONIZER_ALRAM_SEN      , DEF_ON);
// 	g_IO.SetSimulDi(DI_LOAD_TABLE2_IONIZER_ALRAM_SEN      , DEF_ON);
// 	g_IO.SetSimulDi(DI_LOAD_TABLE1_IONIZER_FAN_ALRAM_SEN  , DEF_ON);
// 	g_IO.SetSimulDi(DI_LOAD_TABLE2_IONIZER_FAN_ALRAM_SEN  , DEF_ON);
	
	
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_F1, DEF_ON);
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_R1, DEF_ON);
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP1_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP2_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP3_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP4_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP5_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP6_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP7_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_UP8_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN1_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN2_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN3_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN4_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN5_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN6_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN7_DEVICE_SEN_R4, DEF_ON );
// 
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_F1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_F2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_F3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_F4, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_R1, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_R2, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_R3, DEF_ON );
// 	g_IO.SetSimulDi( DI_STATION_DOWN8_DEVICE_SEN_R4, DEF_ON );

// 	g_IO.SetSimulDi(DI_2D_BARCODE1_2_RIGHT_SEN, DEF_ON);
// 	g_IO.SetSimulDi(DI_2D_BARCODE3_4_LEFT_SEN, DEF_ON);

	g_IO.SetSimulDi(DI_BARCODE1_FOR_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_BARCODE1_BACK_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_BARCODE2_FOR_SEN, DEF_ON);
	g_IO.SetSimulDi(DI_BARCODE2_BACK_SEN, DEF_ON);
	
	g_IO.SetSimulDi( DI_FRONT_LEFT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi( DI_FRONT_RIGHT_DOORLOCK_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_LEFT_DOORLOCK_SEN, DEF_ON);
// 	g_IO.SetSimulDi( DI_RIGHT_DOORLOCK_SEN, DEF_ON);
	g_IO.SetSimulDi( DI_ALL_DOOR_LOCK_SEN, DEF_ON);

//	g_IO.SetSimulDi(DI_REAR_SW_SEN, FALSE);


// 	for( int i = 0; i < eMaxStackerCount; i++ ) {
// 		g_IO.SetSimulDi( DI_STCKR1_C_TRAY_FRONT_LEFT_LOCK_SEN + i * 16, DEF_ON );
// 		g_IO.SetSimulDi( DI_STCKR1_C_TRAY_REAR_LEFT_LOCK_SEN + i * 16, DEF_ON );
// 		g_IO.SetSimulDi( DI_STCKR1_C_TRAY_FRONT_RIGHT_LOCK_SEN + i * 16, DEF_ON );
// 		g_IO.SetSimulDi( DI_STCKR1_C_TRAY_REAR_RIGHT_LOCK_SEN + i * 16, DEF_ON );
// 	}

// 	g_IO.SetSimulDi(DI_BUFFER_TABLE1_DEVICE1_SEN, DEF_ON);
// 	g_IO.SetSimulDi(DI_BUFFER_TABLE1_DEVICE2_SEN, DEF_ON);
// 	g_IO.SetSimulDi(DI_BUFFER_TABLE2_DEVICE1_SEN, DEF_ON);
// 	g_IO.SetSimulDi(DI_BUFFER_TABLE2_DEVICE2_SEN, DEF_ON);

// 	BOOL bOtionDoor = g_DMCont.m_dmEQP.GB(BDM0_MD_FRONT_SLIDE_DOOR);
// 	if (bOtionDoor == TRUE) {
// 		g_IO.SetSimulDi(DI_FRONT_SLIDE_LEFT_DOORLOCK_SEN, DEF_ON);
// 		g_IO.SetSimulDi(DI_FRONT_SLIDE_RIGHT_DOORLOCK_SEN, DEF_ON);
// 	}	

	return TRUE;  // return TRUE unless you set the focus to a control
	// 예외: OCX 속성 페이지는 FALSE를 반환해야 합니다.
}


void CDlgSimulDioSLT::OnDestroy()
{
	CDialogEx::OnDestroy();

	// TODO: 여기에 메시지 처리기 코드를 추가합니다.
}


void CDlgSimulDioSLT::OnShowWindow(BOOL bShow, UINT nStatus)
{
	CDialogEx::OnShowWindow(bShow, nStatus);

	// TODO: 여기에 메시지 처리기 코드를 추가합니다.
}


void CDlgSimulDioSLT::OnTimer(UINT_PTR nIDEvent)
{
	switch( nIDEvent )
	{
	case TID_DOSIMUL_DO_DOORLOCK_ON:
	case TID_DOSIMUL_DO_DOORLOCK_OFF:
		{
			KillTimer( nIDEvent );
		}break;
		//	case TID_DO_C_TRAY_HAND_PICKER1_1_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER1_2_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER1_3_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER1_4_DOWN_ON:
		//		{
		//			KillTimer( nIDEvent );
		//			g_IO.SetSimulDi( DI_C_TRAY_HAND_PICKER_REAR_DOWN_SEN, TRUE );
		//		}break;
		//	case TID_DO_C_TRAY_HAND_PICKER1_1_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER1_2_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER1_3_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER1_4_DOWN_OFF:
		//		{
		//			KillTimer( nIDEvent );
		//			g_IO.SetSimulDi( DI_C_TRAY_HAND_PICKER_REAR_DOWN_SEN, FALSE );
		//		}break;
		//	case TID_DO_C_TRAY_HAND_PICKER2_1_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER2_2_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER2_3_DOWN_ON:
		//	case TID_DO_C_TRAY_HAND_PICKER2_4_DOWN_ON:
		//		{
		//			KillTimer( nIDEvent );
		//			g_IO.SetSimulDi( DI_C_TRAY_HAND_PICKER_FRONT_DOWN_SEN, TRUE );
		//		}break;
		//	case TID_DO_C_TRAY_HAND_PICKER2_1_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER2_2_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER2_3_DOWN_OFF:
		//	case TID_DO_C_TRAY_HAND_PICKER2_4_DOWN_OFF:
		//		{
		//			KillTimer( nIDEvent );
		//			g_IO.SetSimulDi( DI_C_TRAY_HAND_PICKER_FRONT_DOWN_SEN, FALSE );
		//		}break;

			//////////////////////////////////////////////////////////////////////////
			//==== [Test PP#1] ====//
// 	case TID_DO_TEST_HAND1_PICKER_F1_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F1_UP_SEN, DI_TEST_HAND1_PICKER_F1_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F1_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F1_UP_SEN, DI_TEST_HAND1_PICKER_F1_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F2_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F2_UP_SEN, DI_TEST_HAND1_PICKER_F2_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F2_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F2_UP_SEN, DI_TEST_HAND1_PICKER_F2_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F3_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F3_UP_SEN, DI_TEST_HAND1_PICKER_F3_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F3_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F3_UP_SEN, DI_TEST_HAND1_PICKER_F3_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F4_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F4_UP_SEN, DI_TEST_HAND1_PICKER_F4_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_F4_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_F4_UP_SEN, DI_TEST_HAND1_PICKER_F4_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R1_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R1_UP_SEN, DI_TEST_HAND1_PICKER_R1_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R1_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R1_UP_SEN, DI_TEST_HAND1_PICKER_R1_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R2_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R2_UP_SEN, DI_TEST_HAND1_PICKER_R2_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R2_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R2_UP_SEN, DI_TEST_HAND1_PICKER_R2_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R3_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R3_UP_SEN, DI_TEST_HAND1_PICKER_R3_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R3_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R3_UP_SEN, DI_TEST_HAND1_PICKER_R3_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R4_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R4_UP_SEN, DI_TEST_HAND1_PICKER_R4_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_PICKER_R4_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND1_PICKER_R4_UP_SEN, DI_TEST_HAND1_PICKER_R4_DOWN_SEN, DEF_OFF ); break;
// 
// 		//////////////////////////////////////////////////////////////////////////
// 		//==== [Test PP#2] ====//
// 	case TID_DO_TEST_HAND2_PICKER_F1_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F1_UP_SEN, DI_TEST_HAND2_PICKER_F1_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F1_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F1_UP_SEN, DI_TEST_HAND2_PICKER_F1_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F2_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F2_UP_SEN, DI_TEST_HAND2_PICKER_F2_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F2_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F2_UP_SEN, DI_TEST_HAND2_PICKER_F2_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F3_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F3_UP_SEN, DI_TEST_HAND2_PICKER_F3_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F3_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F3_UP_SEN, DI_TEST_HAND2_PICKER_F3_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F4_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F4_UP_SEN, DI_TEST_HAND2_PICKER_F4_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_F4_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_F4_UP_SEN, DI_TEST_HAND2_PICKER_F4_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R1_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R1_UP_SEN, DI_TEST_HAND2_PICKER_R1_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R1_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R1_UP_SEN, DI_TEST_HAND2_PICKER_R1_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R2_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R2_UP_SEN, DI_TEST_HAND2_PICKER_R2_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R2_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R2_UP_SEN, DI_TEST_HAND2_PICKER_R2_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R3_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R3_UP_SEN, DI_TEST_HAND2_PICKER_R3_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R3_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R3_UP_SEN, DI_TEST_HAND2_PICKER_R3_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R4_UP_ON:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R4_UP_SEN, DI_TEST_HAND2_PICKER_R4_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_PICKER_R4_UP_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_TEST_HAND2_PICKER_R4_UP_SEN, DI_TEST_HAND2_PICKER_R4_DOWN_SEN, DEF_OFF ); break;
// 
// 
// 		//////////////////////////////////////////////
// 		// === [Test PP#1] Vacuum/Blow
// 	case TID_DO_TEST_HAND1_F1_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F1_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F1_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_F2_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F2_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F2_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_F3_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F3_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F3_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_F4_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F4_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F4_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_R1_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R1_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R1_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_R2_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R2_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R2_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_R3_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R3_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R3_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_R4_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R4_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R4_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND1_F1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_F4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_F4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND1_R4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND1_R4_VACUUM_SEN, DEF_ON ); break;
// 
// 		//////////////////////////////////////////////
// 		// === [Test PP#2] Vacuum/Blow.
// 	case TID_DO_TEST_HAND2_F1_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F1_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F1_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_F2_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F2_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F2_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_F3_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F3_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F3_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_F4_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F4_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F4_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_R1_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R1_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R1_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_R2_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R2_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R2_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_R3_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R3_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R3_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_R4_VACUUM_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R4_VACUUM_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R4_VACUUM_SEN, DEF_OFF ); break;
// 	case TID_DO_TEST_HAND2_F1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_F4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_F4_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R1_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R2_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R3_VACUUM_SEN, DEF_ON ); break;
// 	case TID_DO_TEST_HAND2_R4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_TEST_HAND2_R4_VACUUM_SEN, DEF_ON ); break;


		//////////////////////////////////////////////////////////////////////////
		// C-Tray
	//case TID_DO_C_TRAY_HAND_VACUUM_F1_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F1_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F1_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F1_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F2_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F2_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F2_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F2_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F3_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F3_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F3_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F3_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F4_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F4_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_F4_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F4_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R1_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R1_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R1_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R1_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R2_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R2_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R2_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R2_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R3_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R3_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R3_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R3_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R4_ON:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R4_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_VACUUM_R4_OFF:	SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R4_VACUUM_SEN, DEF_OFF ); break;
	//case TID_DO_C_TRAY_HAND_F1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F1_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_F2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F2_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_F3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F3_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_F4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_F4_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_R1_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R1_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_R2_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R2_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_R3_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R3_VACUUM_SEN, DEF_ON ); break;
	//case TID_DO_C_TRAY_HAND_R4_BLOW_ON:		SetSimul_IO_One_OnOff( nIDEvent, DI_C_TRAY_HAND_R4_VACUUM_SEN, DEF_ON ); break;




	//////////////////////////////////////////////////////////////////////////
	// Stacker
// 	case TID_DO_STACKER1_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR1_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER1_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR1_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER2_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR2_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER2_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR2_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER3_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR3_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER3_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR3_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER4_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR4_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER4_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR4_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER5_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR5_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER5_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR5_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER6_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR6_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER6_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR6_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER7_MAIN_PUSHER_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR7_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER7_MAIN_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_MAIN_PUSHER_UP_SEN, DI_STCKR7_C_TRAY_MAIN_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 
// 	case TID_DO_STACKER1_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR1_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER1_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR1_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER2_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR2_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER2_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR2_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER3_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR3_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER3_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR3_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER4_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR4_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER4_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR4_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER5_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR5_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER5_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR5_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER6_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR6_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER6_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR6_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_STACKER7_SUB_PUSHER_UP:				SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR7_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_STACKER7_SUB_PUSHER_DOWN:			SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_SUB_PUSHER_UP_SEN, DI_STCKR7_C_TRAY_SUB_PUSHER_DOWN_SEN, DEF_OFF ); break;
// 
// 	case TID_DO_STACKER1_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;
// 	case TID_DO_STACKER1_C_TRAY_UNLOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR1_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER2_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER2_C_TRAY_UNLOCK:			
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR2_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER3_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER3_C_TRAY_UNLOCK:			 
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR3_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER4_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER4_C_TRAY_UNLOCK:			 
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR4_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER5_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER5_C_TRAY_UNLOCK:			
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR5_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER6_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER6_C_TRAY_UNLOCK:			 
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR6_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STACKER7_C_TRAY_LOCK:
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_ON );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_ON );
// 		break;									 
// 	case TID_DO_STACKER7_C_TRAY_UNLOCK:			
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_FRONT_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_FRONT_RIGHT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_REAR_LEFT_LOCK_SEN, DEF_OFF );
// 		SetSimul_IO_One_OnOff( nIDEvent, DI_STCKR7_C_TRAY_REAR_RIGHT_LOCK_SEN, DEF_OFF );
// 		break;
// 	case TID_DO_STCKR1_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_ALIGN_FOR_SEN, DI_STCKR1_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR1_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR1_C_TRAY_ALIGN_FOR_SEN, DI_STCKR1_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR2_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_ALIGN_FOR_SEN, DI_STCKR2_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR2_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR2_C_TRAY_ALIGN_FOR_SEN, DI_STCKR2_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR3_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_ALIGN_FOR_SEN, DI_STCKR3_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR3_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR3_C_TRAY_ALIGN_FOR_SEN, DI_STCKR3_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR4_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_ALIGN_FOR_SEN, DI_STCKR4_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR4_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR4_C_TRAY_ALIGN_FOR_SEN, DI_STCKR4_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR5_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_ALIGN_FOR_SEN, DI_STCKR5_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR5_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR5_C_TRAY_ALIGN_FOR_SEN, DI_STCKR5_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR6_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_ALIGN_FOR_SEN, DI_STCKR6_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR6_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR6_C_TRAY_ALIGN_FOR_SEN, DI_STCKR6_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 	case TID_DO_STCKR7_CV_C_TRAY_ALIGN_ON:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_ALIGN_FOR_SEN, DI_STCKR7_C_TRAY_ALIGN_BACK_SEN, DEF_ON ); break;
// 	case TID_DO_STCKR7_CV_C_TRAY_ALIGN_OFF:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STCKR7_C_TRAY_ALIGN_FOR_SEN, DI_STCKR7_C_TRAY_ALIGN_BACK_SEN, DEF_OFF ); break;
// 		

	//////////////////////////////////////////////////////////////////////////
	// Transfer

// 	case TID_DO_TRANSFER_HEAD_C_TRAY_Z_UP:			SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_UP_SEN, DI_TRANSFER_Z_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_TRANSFER_HEAD_C_TRAY_Z_DOWN:		SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_UP_SEN, DI_TRANSFER_Z_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_ON:		
// 		SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_L_CLAMP_SEN, DI_TRANSFER_Z_L_UNCLAMP_SEN, DEF_ON ); 
// 		SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_R_CLAMP_SEN, DI_TRANSFER_Z_R_UNCLAMP_SEN, DEF_ON );	break;
// 	case TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_OFF:		
// 		SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_L_CLAMP_SEN, DI_TRANSFER_Z_L_UNCLAMP_SEN, DEF_OFF );
// 		SetSimul_IO_Two_OnOff( nIDEvent, DI_TRANSFER_Z_R_CLAMP_SEN, DI_TRANSFER_Z_R_UNCLAMP_SEN, DEF_OFF );	break;
// 
// 	case TID_DO_2D_BARCODE1_2_LEFT: case TID_DO_2D_BARCODE1_2_RIGHT:
// 		{
// 			KillTimer( nIDEvent );
// 			BOOL bSetVal = ( nIDEvent == TID_DO_2D_BARCODE1_2_LEFT );
// 			g_IO.SetSimulDi( DI_2D_BARCODE1_2_LEFT_SEN, bSetVal );
// 			g_IO.SetSimulDi( DI_2D_BARCODE1_2_RIGHT_SEN, !bSetVal );
// 		}break;
// 	case TID_DO_2D_BARCODE3_4_LEFT: case TID_DO_2D_BARCODE3_4_RIGHT:
// 		{
// 			KillTimer( nIDEvent );
// 			BOOL bSetVal = ( nIDEvent == TID_DO_2D_BARCODE3_4_LEFT );
// 			g_IO.SetSimulDi( DI_2D_BARCODE3_4_LEFT_SEN, bSetVal );
// 			g_IO.SetSimulDi( DI_2D_BARCODE3_4_RIGHT_SEN, !bSetVal );
// 		}break;
// 
// 		//////////////////////////////////////////////////////////////////////////
// 		// Press Unit
// 	case TID_DO_ANTIViBRATOR_SITE1_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN1_ANTI_VIB_UP_SEN, DI_STATION_DOWN1_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE1_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN1_ANTI_VIB_UP_SEN, DI_STATION_DOWN1_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE2_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN2_ANTI_VIB_UP_SEN, DI_STATION_DOWN2_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE2_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN2_ANTI_VIB_UP_SEN, DI_STATION_DOWN2_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE3_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN3_ANTI_VIB_UP_SEN, DI_STATION_DOWN3_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE3_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN3_ANTI_VIB_UP_SEN, DI_STATION_DOWN3_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE4_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN4_ANTI_VIB_UP_SEN, DI_STATION_DOWN4_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE4_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN4_ANTI_VIB_UP_SEN, DI_STATION_DOWN4_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE5_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN5_ANTI_VIB_UP_SEN, DI_STATION_DOWN5_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE5_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN5_ANTI_VIB_UP_SEN, DI_STATION_DOWN5_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE6_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN6_ANTI_VIB_UP_SEN, DI_STATION_DOWN6_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE6_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN6_ANTI_VIB_UP_SEN, DI_STATION_DOWN6_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE7_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN7_ANTI_VIB_UP_SEN, DI_STATION_DOWN7_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE7_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN7_ANTI_VIB_UP_SEN, DI_STATION_DOWN7_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE8_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN8_ANTI_VIB_UP_SEN, DI_STATION_DOWN8_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE8_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_DOWN8_ANTI_VIB_UP_SEN, DI_STATION_DOWN8_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 
// 	case TID_DO_ANTIViBRATOR_SITE9_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP1_ANTI_VIB_UP_SEN, DI_STATION_UP1_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE9_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP1_ANTI_VIB_UP_SEN, DI_STATION_UP1_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE10_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP2_ANTI_VIB_UP_SEN, DI_STATION_UP2_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE10_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP2_ANTI_VIB_UP_SEN, DI_STATION_UP2_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE11_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP3_ANTI_VIB_UP_SEN, DI_STATION_UP3_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE11_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP3_ANTI_VIB_UP_SEN, DI_STATION_UP3_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE12_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP4_ANTI_VIB_UP_SEN, DI_STATION_UP4_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE12_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP4_ANTI_VIB_UP_SEN, DI_STATION_UP4_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE13_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP5_ANTI_VIB_UP_SEN, DI_STATION_UP5_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE13_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP5_ANTI_VIB_UP_SEN, DI_STATION_UP5_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE14_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP6_ANTI_VIB_UP_SEN, DI_STATION_UP6_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE14_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP6_ANTI_VIB_UP_SEN, DI_STATION_UP6_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE15_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP7_ANTI_VIB_UP_SEN, DI_STATION_UP7_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE15_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP7_ANTI_VIB_UP_SEN, DI_STATION_UP7_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
// 	case TID_DO_ANTIViBRATOR_SITE16_UP:		SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP8_ANTI_VIB_UP_SEN, DI_STATION_UP8_ANTI_VIB_DOWN_SEN, DEF_ON ); break;
// 	case TID_DO_ANTIViBRATOR_SITE16_DOWN:	SetSimul_IO_Two_OnOff( nIDEvent, DI_STATION_UP8_ANTI_VIB_UP_SEN, DI_STATION_UP8_ANTI_VIB_DOWN_SEN, DEF_OFF ); break;
	}

	CDialogEx::OnTimer(nIDEvent);
}

// WPARAM : DO Index
// LPARAM : new value (0=off, 1=on)
LRESULT CDlgSimulDioSLT::RcvChangedDo(WPARAM wParam, LPARAM lParam)
{
	switch( wParam )
	{
	case DO_FRONT_LEFT_DOORLOCK:
	case DO_FRONT_RIGHT_DOORLOCK:
	case DO_HINGED_RIGHT_DOORLOCK:
	case DO_SLIDE_RIGHT_F1_DOORLOCK:
	case DO_SLIDE_RIGHT_R2_DOORLOCK:
	case DO_REAR_RIGHT_DOORLOCK:
	case DO_REAR_LEFT_DOORLOCK:
	case DO_SLIDE_LEFT_R2_DOORLOCK:
	case DO_SLIDE_LEFT_F1_DOORLOCK:
	case DO_HINGED_LEFT_DOORLOCK:
		//	case DO_PC_DOORLOCK :
		{
			int nTID = ( lParam == TRUE ) ? TID_DOSIMUL_DO_DOORLOCK_ON : TID_DOSIMUL_DO_DOORLOCK_OFF;
			SetTimer( nTID, 50, NULL );
		}break;

		//////////////////////////////////////////////////////////////////////////
		//======== Test PP #1 - #2
// 	case DO_TEST_HAND1_PICKER_F1_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_F1_UP_OFF, TID_DO_TEST_HAND1_PICKER_F1_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_F2_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_F2_UP_OFF, TID_DO_TEST_HAND1_PICKER_F2_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_F3_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_F3_UP_OFF, TID_DO_TEST_HAND1_PICKER_F3_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_F4_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_F4_UP_OFF, TID_DO_TEST_HAND1_PICKER_F4_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_R1_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_R1_UP_OFF, TID_DO_TEST_HAND1_PICKER_R1_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_R2_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_R2_UP_OFF, TID_DO_TEST_HAND1_PICKER_R2_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_R3_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_R3_UP_OFF, TID_DO_TEST_HAND1_PICKER_R3_UP_ON ); break;
// 	case DO_TEST_HAND1_PICKER_R4_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_PICKER_R4_UP_OFF, TID_DO_TEST_HAND1_PICKER_R4_UP_ON ); break;
// 
// 	case DO_TEST_HAND2_PICKER_F1_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_F1_UP_OFF, TID_DO_TEST_HAND2_PICKER_F1_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_F2_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_F2_UP_OFF, TID_DO_TEST_HAND2_PICKER_F2_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_F3_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_F3_UP_OFF, TID_DO_TEST_HAND2_PICKER_F3_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_F4_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_F4_UP_OFF, TID_DO_TEST_HAND2_PICKER_F4_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_R1_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_R1_UP_OFF, TID_DO_TEST_HAND2_PICKER_R1_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_R2_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_R2_UP_OFF, TID_DO_TEST_HAND2_PICKER_R2_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_R3_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_R3_UP_OFF, TID_DO_TEST_HAND2_PICKER_R3_UP_ON ); break;
// 	case DO_TEST_HAND2_PICKER_R4_DOWN:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_PICKER_R4_UP_OFF, TID_DO_TEST_HAND2_PICKER_R4_UP_ON ); break;
// 
// 		//////////////////////////////////////////////////////////////////////////
// 		//=== Test PP #1 - #2 Vacuum/Blow 
// 	case DO_TEST_HAND1_F1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F1_VACUUM_ON, TID_DO_TEST_HAND1_F1_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_F2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F2_VACUUM_ON, TID_DO_TEST_HAND1_F2_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_F3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F3_VACUUM_ON, TID_DO_TEST_HAND1_F3_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_F4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F4_VACUUM_ON, TID_DO_TEST_HAND1_F4_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_R1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R1_VACUUM_ON, TID_DO_TEST_HAND1_R1_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_R2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R2_VACUUM_ON, TID_DO_TEST_HAND1_R2_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_R3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R3_VACUUM_ON, TID_DO_TEST_HAND1_R3_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_R4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R4_VACUUM_ON, TID_DO_TEST_HAND1_R4_VACUUM_OFF ); break;
// 	case DO_TEST_HAND1_F1_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F1_BLOW_ON, TID_DO_TEST_HAND1_F1_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_F2_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F2_BLOW_ON, TID_DO_TEST_HAND1_F2_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_F3_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F3_BLOW_ON, TID_DO_TEST_HAND1_F3_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_F4_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_F4_BLOW_ON, TID_DO_TEST_HAND1_F4_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_R1_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R1_BLOW_ON, TID_DO_TEST_HAND1_R1_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_R2_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R2_BLOW_ON, TID_DO_TEST_HAND1_R2_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_R3_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R3_BLOW_ON, TID_DO_TEST_HAND1_R3_BLOW_OFF ); break;
// 	case DO_TEST_HAND1_R4_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND1_R4_BLOW_ON, TID_DO_TEST_HAND1_R4_BLOW_OFF ); break;
// 
// 	case DO_TEST_HAND2_F1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F1_VACUUM_ON, TID_DO_TEST_HAND2_F1_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_F2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F2_VACUUM_ON, TID_DO_TEST_HAND2_F2_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_F3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F3_VACUUM_ON, TID_DO_TEST_HAND2_F3_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_F4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F4_VACUUM_ON, TID_DO_TEST_HAND2_F4_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_R1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R1_VACUUM_ON, TID_DO_TEST_HAND2_R1_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_R2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R2_VACUUM_ON, TID_DO_TEST_HAND2_R2_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_R3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R3_VACUUM_ON, TID_DO_TEST_HAND2_R3_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_R4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R4_VACUUM_ON, TID_DO_TEST_HAND2_R4_VACUUM_OFF ); break;
// 	case DO_TEST_HAND2_F1_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F1_BLOW_ON, TID_DO_TEST_HAND2_F1_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_F2_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F2_BLOW_ON, TID_DO_TEST_HAND2_F2_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_F3_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F3_BLOW_ON, TID_DO_TEST_HAND2_F3_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_F4_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_F4_BLOW_ON, TID_DO_TEST_HAND2_F4_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_R1_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R1_BLOW_ON, TID_DO_TEST_HAND2_R1_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_R2_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R2_BLOW_ON, TID_DO_TEST_HAND2_R2_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_R3_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R3_BLOW_ON, TID_DO_TEST_HAND2_R3_BLOW_OFF ); break;
// 	case DO_TEST_HAND2_R4_BLOW:			SetSimulTimer_On( lParam, TID_DO_TEST_HAND2_R4_BLOW_ON, TID_DO_TEST_HAND2_R4_BLOW_OFF ); break;

		//////////////////////////////////////////////////////////////////////////
		// C-Tray PP
	//case DO_C_TRAY_HAND_F1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_F1_ON, TID_DO_C_TRAY_HAND_VACUUM_F1_OFF ); break;
	//case DO_C_TRAY_HAND_F2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_F2_ON, TID_DO_C_TRAY_HAND_VACUUM_F2_OFF ); break;
	//case DO_C_TRAY_HAND_F3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_F3_ON, TID_DO_C_TRAY_HAND_VACUUM_F3_OFF ); break;
	//case DO_C_TRAY_HAND_F4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_F4_ON, TID_DO_C_TRAY_HAND_VACUUM_F4_OFF ); break;
	//case DO_C_TRAY_HAND_R1_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_R1_ON, TID_DO_C_TRAY_HAND_VACUUM_R1_OFF ); break;
	//case DO_C_TRAY_HAND_R2_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_R2_ON, TID_DO_C_TRAY_HAND_VACUUM_R2_OFF ); break;
	//case DO_C_TRAY_HAND_R3_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_R3_ON, TID_DO_C_TRAY_HAND_VACUUM_R3_OFF ); break;
	//case DO_C_TRAY_HAND_R4_VACUUM_SET:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_VACUUM_R4_ON, TID_DO_C_TRAY_HAND_VACUUM_R4_OFF ); break;
	//case DO_C_TRAY_HAND_F1_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_F1_BLOW_ON, TID_DO_C_TRAY_HAND_F1_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_F2_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_F2_BLOW_ON, TID_DO_C_TRAY_HAND_F2_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_F3_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_F3_BLOW_ON, TID_DO_C_TRAY_HAND_F3_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_F4_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_F4_BLOW_ON, TID_DO_C_TRAY_HAND_F4_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_R1_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_R1_BLOW_ON, TID_DO_C_TRAY_HAND_R1_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_R2_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_R2_BLOW_ON, TID_DO_C_TRAY_HAND_R2_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_R3_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_R3_BLOW_ON, TID_DO_C_TRAY_HAND_R3_BLOW_OFF ); break;
	//case DO_C_TRAY_HAND_R4_BLOW:		SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_R4_BLOW_ON, TID_DO_C_TRAY_HAND_R4_BLOW_OFF ); break;



// 	case DO_C_TRAY_HAND_PICKER_F1_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_F1_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_F1_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_F2_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_F2_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_F2_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_F3_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_F3_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_F3_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_F4_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_F4_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_F4_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_R1_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_R1_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_R1_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_R2_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_R2_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_R2_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_R3_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_R3_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_R3_DOWN_OFF ); break;
// 	case DO_C_TRAY_HAND_PICKER_R4_DOWN:	SetSimulTimer_On( lParam, TID_DO_C_TRAY_HAND_PICKER_R4_DOWN_ON, TID_DO_C_TRAY_HAND_PICKER_R4_DOWN_OFF ); break;


		//////////////////////////////////////////////////////////////////////////
		//-- Stacker
	//case DO_STCKR1_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER1_MAIN_PUSHER_UP, TID_DO_STACKER1_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR1_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER1_MAIN_PUSHER_DOWN, TID_DO_STACKER1_MAIN_PUSHER_UP ); break;
	//case DO_STCKR2_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER2_MAIN_PUSHER_UP, TID_DO_STACKER2_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR2_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER2_MAIN_PUSHER_DOWN, TID_DO_STACKER2_MAIN_PUSHER_UP ); break;
	//case DO_STCKR3_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER3_MAIN_PUSHER_UP, TID_DO_STACKER3_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR3_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER3_MAIN_PUSHER_DOWN, TID_DO_STACKER3_MAIN_PUSHER_UP ); break;
	//case DO_STCKR4_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER4_MAIN_PUSHER_UP, TID_DO_STACKER4_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR4_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER4_MAIN_PUSHER_DOWN, TID_DO_STACKER4_MAIN_PUSHER_UP ); break;
	//case DO_STCKR5_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER5_MAIN_PUSHER_UP, TID_DO_STACKER5_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR5_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER5_MAIN_PUSHER_DOWN, TID_DO_STACKER5_MAIN_PUSHER_UP ); break;
	//case DO_STCKR6_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER6_MAIN_PUSHER_UP, TID_DO_STACKER6_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR6_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER6_MAIN_PUSHER_DOWN, TID_DO_STACKER6_MAIN_PUSHER_UP ); break;
	//case DO_STCKR7_C_TRAY_MAIN_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER7_MAIN_PUSHER_UP, TID_DO_STACKER7_MAIN_PUSHER_DOWN ); break;
	//case DO_STCKR7_C_TRAY_MAIN_PUSHER_DOWN: SetSimulTimer_On( lParam, TID_DO_STACKER7_MAIN_PUSHER_DOWN, TID_DO_STACKER7_MAIN_PUSHER_UP ); break;

	//case DO_STCKR1_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER1_SUB_PUSHER_UP, TID_DO_STACKER1_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR1_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER1_SUB_PUSHER_DOWN, TID_DO_STACKER1_SUB_PUSHER_UP ); break;
	//case DO_STCKR2_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER2_SUB_PUSHER_UP, TID_DO_STACKER2_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR2_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER2_SUB_PUSHER_DOWN, TID_DO_STACKER2_SUB_PUSHER_UP ); break;
	//case DO_STCKR3_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER3_SUB_PUSHER_UP, TID_DO_STACKER3_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR3_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER3_SUB_PUSHER_DOWN, TID_DO_STACKER3_SUB_PUSHER_UP ); break;
	//case DO_STCKR4_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER4_SUB_PUSHER_UP, TID_DO_STACKER4_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR4_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER4_SUB_PUSHER_DOWN, TID_DO_STACKER4_SUB_PUSHER_UP ); break;
	//case DO_STCKR5_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER5_SUB_PUSHER_UP, TID_DO_STACKER5_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR5_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER5_SUB_PUSHER_DOWN, TID_DO_STACKER5_SUB_PUSHER_UP ); break;
	//case DO_STCKR6_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER6_SUB_PUSHER_UP, TID_DO_STACKER6_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR6_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER6_SUB_PUSHER_DOWN, TID_DO_STACKER6_SUB_PUSHER_UP ); break;
	//case DO_STCKR7_C_TRAY_SUB_PUSHER_UP:	SetSimulTimer_On( lParam, TID_DO_STACKER7_SUB_PUSHER_UP, TID_DO_STACKER7_SUB_PUSHER_DOWN ); break;
	//case DO_STCKR7_C_TRAY_SUB_PUSHER_DOWN:	SetSimulTimer_On( lParam, TID_DO_STACKER7_SUB_PUSHER_DOWN, TID_DO_STACKER7_SUB_PUSHER_UP ); break;

	//case DO_STCKR1_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER1_C_TRAY_LOCK, TID_DO_STACKER1_C_TRAY_UNLOCK ); break;
	//case DO_STCKR1_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER1_C_TRAY_UNLOCK, TID_DO_STACKER1_C_TRAY_LOCK ); break;
	//case DO_STCKR2_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER2_C_TRAY_LOCK, TID_DO_STACKER2_C_TRAY_UNLOCK ); break;
	//case DO_STCKR2_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER2_C_TRAY_UNLOCK, TID_DO_STACKER2_C_TRAY_LOCK ); break;
	//case DO_STCKR3_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER3_C_TRAY_LOCK, TID_DO_STACKER3_C_TRAY_UNLOCK ); break;
	//case DO_STCKR3_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER3_C_TRAY_UNLOCK, TID_DO_STACKER3_C_TRAY_LOCK ); break;
	//case DO_STCKR4_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER4_C_TRAY_LOCK, TID_DO_STACKER4_C_TRAY_UNLOCK ); break;
	//case DO_STCKR4_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER4_C_TRAY_UNLOCK, TID_DO_STACKER4_C_TRAY_LOCK ); break;
	//case DO_STCKR5_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER5_C_TRAY_LOCK, TID_DO_STACKER5_C_TRAY_UNLOCK ); break;
	//case DO_STCKR5_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER5_C_TRAY_UNLOCK, TID_DO_STACKER5_C_TRAY_LOCK ); break;
	//case DO_STCKR6_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER6_C_TRAY_LOCK, TID_DO_STACKER6_C_TRAY_UNLOCK ); break;
	//case DO_STCKR6_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER6_C_TRAY_UNLOCK, TID_DO_STACKER6_C_TRAY_LOCK ); break;
	//case DO_STCKR7_C_TRAY_LOCK: SetSimulTimer_On( lParam, TID_DO_STACKER7_C_TRAY_LOCK, TID_DO_STACKER7_C_TRAY_UNLOCK ); break;
	//case DO_STCKR7_C_TRAY_UNLOCK: SetSimulTimer_On( lParam, TID_DO_STACKER7_C_TRAY_UNLOCK, TID_DO_STACKER7_C_TRAY_LOCK ); break;

	//case DO_STCKR1_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR1_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR1_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR2_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR2_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR2_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR3_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR3_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR3_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR4_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR4_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR4_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR5_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR5_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR5_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR6_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR6_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR6_CV_C_TRAY_ALIGN_OFF ); break;
	//case DO_STCKR7_CV_C_TRAY_ALIGN: SetSimulTimer_On( lParam, TID_DO_STCKR7_CV_C_TRAY_ALIGN_ON, TID_DO_STCKR7_CV_C_TRAY_ALIGN_OFF ); break;




		//////////////////////////////////////////////////////////////////////////
		// Transfer
// 	case DO_TRANSFER_Z_UP:			SetSimulTimer_On( lParam, TID_DO_TRANSFER_HEAD_C_TRAY_Z_UP,	  TID_DO_TRANSFER_HEAD_C_TRAY_Z_DOWN ); break;
// 	case DO_TRANSFER_Z_DOWN:		SetSimulTimer_On( lParam, TID_DO_TRANSFER_HEAD_C_TRAY_Z_DOWN, TID_DO_TRANSFER_HEAD_C_TRAY_Z_UP ); break;
// 
// 	case DO_TRANSFER_C_TRAY_CLAMP:		SetSimulTimer_On( lParam, TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_ON, TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_OFF ); break;
// 	case DO_TRANSFER_C_TRAY_UNCLAMP:	SetSimulTimer_On( lParam, TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_OFF, TID_DO_TRANSFER_HEAD_C_TRAY_CLAMP_ON ); break;
// 
// 	case DO_2D_BARCODE1_2_LEFT:	SetSimulTimer_On( lParam, TID_DO_2D_BARCODE1_2_LEFT, TID_DO_2D_BARCODE1_2_RIGHT ); break;
// 	case DO_2D_BARCODE1_2_RIGHT:SetSimulTimer_On( lParam, TID_DO_2D_BARCODE1_2_RIGHT, TID_DO_2D_BARCODE1_2_LEFT ); break;
// 	case DO_2D_BARCODE3_4_LEFT:SetSimulTimer_On( lParam, TID_DO_2D_BARCODE3_4_LEFT, TID_DO_2D_BARCODE3_4_RIGHT ); break;
// 	case DO_2D_BARCODE3_4_RIGHT:SetSimulTimer_On( lParam, TID_DO_2D_BARCODE3_4_RIGHT, TID_DO_2D_BARCODE3_4_LEFT ); break;
// 
// 		//////////////////////////////////////////////////////////////////////////
// 		// Press Unit
// 	case DO_STATION_DOWN1_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE1_UP, TID_DO_ANTIViBRATOR_SITE1_DOWN ); break;
// 	case DO_STATION_DOWN1_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE1_DOWN, TID_DO_ANTIViBRATOR_SITE1_UP ); break;
// 	case DO_STATION_DOWN2_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE2_UP, TID_DO_ANTIViBRATOR_SITE2_DOWN ); break;
// 	case DO_STATION_DOWN2_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE2_DOWN, TID_DO_ANTIViBRATOR_SITE2_UP ); break;
// 	case DO_STATION_DOWN3_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE3_UP, TID_DO_ANTIViBRATOR_SITE3_DOWN ); break;
// 	case DO_STATION_DOWN3_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE3_DOWN, TID_DO_ANTIViBRATOR_SITE3_UP ); break;
// 	case DO_STATION_DOWN4_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE4_UP, TID_DO_ANTIViBRATOR_SITE4_DOWN ); break;
// 	case DO_STATION_DOWN4_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE4_DOWN, TID_DO_ANTIViBRATOR_SITE4_UP ); break;
// 	case DO_STATION_DOWN5_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE5_UP, TID_DO_ANTIViBRATOR_SITE5_DOWN ); break;
// 	case DO_STATION_DOWN5_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE5_DOWN, TID_DO_ANTIViBRATOR_SITE5_UP ); break;
// 	case DO_STATION_DOWN6_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE6_UP, TID_DO_ANTIViBRATOR_SITE6_DOWN ); break;
// 	case DO_STATION_DOWN6_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE6_DOWN, TID_DO_ANTIViBRATOR_SITE6_UP ); break;
// 	case DO_STATION_DOWN7_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE7_UP, TID_DO_ANTIViBRATOR_SITE7_DOWN ); break;
// 	case DO_STATION_DOWN7_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE7_DOWN, TID_DO_ANTIViBRATOR_SITE7_UP ); break;
// 	case DO_STATION_DOWN8_ANTI_VIB_UP:		SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE8_UP, TID_DO_ANTIViBRATOR_SITE8_DOWN ); break;
// 	case DO_STATION_DOWN8_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE8_DOWN, TID_DO_ANTIViBRATOR_SITE8_UP ); break;
// 
// 	case DO_STATION_UP1_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE9_UP, TID_DO_ANTIViBRATOR_SITE9_DOWN ); break;
// 	case DO_STATION_UP1_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE9_DOWN, TID_DO_ANTIViBRATOR_SITE9_UP ); break;
// 	case DO_STATION_UP2_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE10_UP, TID_DO_ANTIViBRATOR_SITE10_DOWN ); break;
// 	case DO_STATION_UP2_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE10_DOWN, TID_DO_ANTIViBRATOR_SITE10_UP ); break;
// 	case DO_STATION_UP3_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE11_UP, TID_DO_ANTIViBRATOR_SITE11_DOWN ); break;
// 	case DO_STATION_UP3_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE11_DOWN, TID_DO_ANTIViBRATOR_SITE11_UP ); break;
// 	case DO_STATION_UP4_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE12_UP, TID_DO_ANTIViBRATOR_SITE12_DOWN ); break;
// 	case DO_STATION_UP4_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE12_DOWN, TID_DO_ANTIViBRATOR_SITE12_UP ); break;
// 	case DO_STATION_UP5_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE13_UP, TID_DO_ANTIViBRATOR_SITE13_DOWN ); break;
// 	case DO_STATION_UP5_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE13_DOWN, TID_DO_ANTIViBRATOR_SITE13_UP ); break;
// 	case DO_STATION_UP6_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE14_UP, TID_DO_ANTIViBRATOR_SITE14_DOWN ); break;
// 	case DO_STATION_UP6_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE14_DOWN, TID_DO_ANTIViBRATOR_SITE14_UP ); break;
// 	case DO_STATION_UP7_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE15_UP, TID_DO_ANTIViBRATOR_SITE15_DOWN ); break;
// 	case DO_STATION_UP7_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE15_DOWN, TID_DO_ANTIViBRATOR_SITE15_UP ); break;
// 	case DO_STATION_UP8_ANTI_VIB_UP:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE16_UP, TID_DO_ANTIViBRATOR_SITE16_DOWN ); break;
// 	case DO_STATION_UP8_ANTI_VIB_DOWN:	SetSimulTimer_On( lParam, TID_DO_ANTIViBRATOR_SITE16_DOWN, TID_DO_ANTIViBRATOR_SITE16_UP ); break;

	}
	return 0L;
}