#if !defined(AFX_DSSPANEL_H__9A04B896_C5BC_4DC0_930B_6F9D5C2BDB1E__INCLUDED_)
#define AFX_DSSPANEL_H__9A04B896_C5BC_4DC0_930B_6F9D5C2BDB1E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COleFont;
class CPicture;

/////////////////////////////////////////////////////////////////////////////
// CDSSPanel wrapper class

class CDSSPanel : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDSSPanel)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x65e6fdc, 0x1bf9, 0x11d2, { 0xba, 0xe8, 0x0, 0x10, 0x4b, 0x9e, 0x7, 0x92 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetActiveColors();
	void SetActiveColors(BOOL);
	short GetPictureAnimationDelay();
	void SetPictureAnimationDelay(short);
	BOOL GetPictureAnimationEnabled();
	void SetPictureAnimationEnabled(BOOL);
	OLE_COLOR GetBackColor();
	void SetBackColor(OLE_COLOR);
	long GetBackStyle();
	void SetBackStyle(long);
	long GetCaptionStyle();
	void SetCaptionStyle(long);
	BOOL GetEnabled();
	void SetEnabled(BOOL);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	long GetFont3D();
	void SetFont3D(long);
	OLE_COLOR GetForeColor();
	void SetForeColor(OLE_COLOR);
	OLE_HANDLE GetHWnd();
	short GetMarqueeDelay();
	void SetMarqueeDelay(short);
	long GetMarqueeDirection();
	void SetMarqueeDirection(long);
	short GetMarqueeScrollAmount();
	void SetMarqueeScrollAmount(short);
	long GetMarqueeStyle();
	void SetMarqueeStyle(long);
	CPicture GetMouseIcon();
	void SetMouseIcon(LPDISPATCH);
	long GetMousePointer();
	void SetMousePointer(long);
	long GetOLEDropMode();
	void SetOLEDropMode(long);
	CPicture GetPicture();
	void SetPicture(LPDISPATCH);
	short GetPictureAnimationCount();
	void SetPictureAnimationCount(short);
	short GetPictureFrame();
	void SetPictureFrame(short);
	short GetPictureFrames();
	void SetPictureFrames(short);
	unsigned long GetPictureMaskColor();
	void SetPictureMaskColor(unsigned long);
	long GetPictureMaskColorSource();
	void SetPictureMaskColorSource(long);
	BOOL GetPictureUseMask();
	void SetPictureUseMask(BOOL);
	VARIANT GetTagVariant();
	void SetTagVariant(const VARIANT&);
	long GetPictureBackgroundStyle();
	void SetPictureBackgroundStyle(long);
	CPicture GetPictureBackground();
	void SetPictureBackground(LPDISPATCH);
	BOOL GetClipControls();
	void SetClipControls(BOOL);
	CString GetCaption();
	void SetCaption(LPCTSTR);
	short GetBevelWidth();
	void SetBevelWidth(short);
	short GetBorderWidth();
	void SetBorderWidth(short);
	long GetBevelOuter();
	void SetBevelOuter(long);
	long GetBevelInner();
	void SetBevelInner(long);
	BOOL GetRoundedCorners();
	void SetRoundedCorners(BOOL);
	BOOL GetOutline();
	void SetOutline(BOOL);
	long GetFloodType();
	void SetFloodType(long);
	unsigned long GetFloodColor();
	void SetFloodColor(unsigned long);
	short GetFloodPercent();
	void SetFloodPercent(short);
	BOOL GetFloodShowPct();
	void SetFloodShowPct(BOOL);
	long GetAlignment();
	void SetAlignment(long);
	long GetAutoSize();
	void SetAutoSize(long);
	long GetPictureAlignment();
	void SetPictureAlignment(long);
	long GetFloodFillStyle();
	void SetFloodFillStyle(long);
	BOOL GetPictureBackgroundUseMask();
	void SetPictureBackgroundUseMask(BOOL);

// Operations
public:
	void On();
	void Off();

	void SetStatus(int nStatus);

	void Refresh();
	void PlaySoundFile(const VARIANT& SoundFile);
	void AboutBox();
	// method 'OLEDrag' not emitted because of invalid return type or parameter type
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DSSPANEL_H__9A04B896_C5BC_4DC0_930B_6F9D5C2BDB1E__INCLUDED_)
