#if !defined(AFX_GRADIENTPROGRESS_H__AA9D7A07_ED83_414F_9C90_48D3CC176D8D__INCLUDED_)
#define AFX_GRADIENTPROGRESS_H__AA9D7A07_ED83_414F_9C90_48D3CC176D8D__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGradientProgress wrapper class

class CGradientProgress : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGradientProgress)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7fad4c65, 0x93f5, 0x11d2, { 0x91, 0x84, 0x0, 0xc0, 0x4f, 0x88, 0x8c, 0x35 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	unsigned long GetBkColor();
	void SetBkColor(unsigned long);
	unsigned long GetNForeColor();
	void SetNForeColor(unsigned long);
	BOOL GetGradientEnable();
	void SetGradientEnable(BOOL);
	BOOL GetShowText();
	void SetShowText(BOOL);
	unsigned long GetStartColor();
	void SetStartColor(unsigned long);
	unsigned long GetEndColor();
	void SetEndColor(unsigned long);
	short GetInset();
	void SetInset(short);

// Operations
public:
	short SetPos(short nPos);
	void SetRange(short nMin, short nMax);
	short GetPos();
	BOOL GetShowTextEnable();
	BOOL GetGridentEnable();
	void ShowWindow(BOOL bEnable);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GRADIENTPROGRESS_H__AA9D7A07_ED83_414F_9C90_48D3CC176D8D__INCLUDED_)
