// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gradientprogress.h"

/////////////////////////////////////////////////////////////////////////////
// CGradientProgress

IMPLEMENT_DYNCREATE(CGradientProgress, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGradientProgress properties

unsigned long CGradientProgress::GetBkColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CGradientProgress::SetBkColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

unsigned long CGradientProgress::GetNForeColor()
{
	unsigned long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CGradientProgress::SetNForeColor(unsigned long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

BOOL CGradientProgress::GetGradientEnable()
{
	BOOL result;
	GetProperty(0x1, VT_BOOL, (void*)&result);
	return result;
}

void CGradientProgress::SetGradientEnable(BOOL propVal)
{
	SetProperty(0x1, VT_BOOL, propVal);
}

BOOL CGradientProgress::GetShowText()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CGradientProgress::SetShowText(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

unsigned long CGradientProgress::GetStartColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CGradientProgress::SetStartColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

unsigned long CGradientProgress::GetEndColor()
{
	unsigned long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CGradientProgress::SetEndColor(unsigned long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

short CGradientProgress::GetInset()
{
	short result;
	GetProperty(0x7, VT_I2, (void*)&result);
	return result;
}

void CGradientProgress::SetInset(short propVal)
{
	SetProperty(0x7, VT_I2, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGradientProgress operations

short CGradientProgress::SetPos(short nPos)
{
	short result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x8, DISPATCH_METHOD, VT_I2, (void*)&result, parms, nPos);
	return result;
}

void CGradientProgress::SetRange(short nMin, short nMax)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 nMin, nMax);
}

short CGradientProgress::GetPos()
{
	short result;
	InvokeHelper(0xa, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

BOOL CGradientProgress::GetShowTextEnable()
{
	BOOL result;
	InvokeHelper(0xb, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

BOOL CGradientProgress::GetGridentEnable()
{
	BOOL result;
	InvokeHelper(0xc, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CGradientProgress::ShowWindow(BOOL bEnable)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 bEnable);
}

void CGradientProgress::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
