// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "nokey.h"

/////////////////////////////////////////////////////////////////////////////
// CNoKey

IMPLEMENT_DYNCREATE(CNoKey, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CNoKey properties

/////////////////////////////////////////////////////////////////////////////
// CNoKey operations

CString CNoKey::GetNo()
{
	CString result;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CNoKey::SetNo(LPCTSTR strValue)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strValue);
}

void CNoKey::OnShow()
{
	InvokeHelper(0x3, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CNoKey::SetTitleName(LPCTSTR strTitleName)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 strTitleName);
}

void CNoKey::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
