#if !defined(AFX_NOKEY_H__DF702DDD_4433_4794_A968_057B17776A16__INCLUDED_)
#define AFX_NOKEY_H__DF702DDD_4433_4794_A968_057B17776A16__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CNoKey wrapper class

class CNoKey : public CWnd
{
protected:
	DECLARE_DYNCREATE(CNoKey)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1dd48b9f, 0x82f6, 0x11d2, { 0x91, 0x84, 0x0, 0xc0, 0x4f, 0x88, 0x8c, 0x35 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString GetNo();
	void SetNo(LPCTSTR strValue);
	void OnShow();
	void SetTitleName(LPCTSTR strTitleName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_NOKEY_H__DF702DDD_4433_4794_A968_057B17776A16__INCLUDED_)
