#pragma once

#define SZ_DM_NAME_7		_T("DM_STACKER")

// Load Stacker와 Unload Stacker가 영역을 두개로 나누어 사용한다.
#define LD_STACKER_BASE    (0x000)
#define UD_STACKER_BASE    (0x200)

#define BDM7_LD_STACKER_EV_TRAY_SEN_CHECK_DISABLE  (0)

#define BDM7_SLT_USE_STACKER1_REAR_SEN_EXIST				(0x001)
#define BDM7_SLT_USE_STACKER2_REAR_SEN_EXIST				(0x002)
#define BDM7_SLT_USE_STACKER3_REAR_SEN_EXIST				(0x003)
#define BDM7_SLT_USE_STACKER4_REAR_SEN_EXIST				(0x004)
#define BDM7_SLT_USE_STACKER5_REAR_SEN_EXIST				(0x005)
#define BDM7_SLT_USE_STACKER6_REAR_SEN_EXIST				(0x006)
#define BDM7_SLT_USE_STACKER7_REAR_SEN_EXIST				(0x007)

#define BDM7_SLT_USE_STACKER1_FRONT_SEN_EXIST				(0x008)
#define BDM7_SLT_USE_STACKER2_FRONT_SEN_EXIST				(0x009)
#define BDM7_SLT_USE_STACKER3_FRONT_SEN_EXIST				(0x00A)
#define BDM7_SLT_USE_STACKER4_FRONT_SEN_EXIST				(0x00B)
#define BDM7_SLT_USE_STACKER5_FRONT_SEN_EXIST				(0x00C)
#define BDM7_SLT_USE_STACKER6_FRONT_SEN_EXIST				(0x00D)
#define BDM7_SLT_USE_STACKER7_FRONT_SEN_EXIST				(0x00E)

//#define BDM7_ULD_SETPLATE1_CHANGE_VIBRATOR        (0x001)
//#define BDM7_ULD_SETPLATE2_CHANGE_VIBRATOR        (0x002)
//#define BDM7_ULD_SETPLATE3_CHANGE_VIBRATOR        (0x003)
//#define BDM7_ULD_SETPLATE4_CHANGE_VIBRATOR        (0x004)

#define BDM7_UD_STACKER_EV_TRAY_SEN_CHECK_DISABLE  (512)


//=========================================== Load Stacker
#define NDM7_LD_STACKER_CLAMP_OPER_TIME_MIN     (0x000)
#define NDM7_LD_STACKER_CLAMP_OPER_TIME_MAX     (0x001)
#define NDM7_LD_STACKER_UNCLAMP_OPER_TIME_MIN   (0x002)
#define NDM7_LD_STACKER_UNCLAMP_OPER_TIME_MAX   (0x003)

#define NDM7_LD_UDR_STACKER1_MAX_TRAY_COUNT     (0x020)



//=========================================== Unload Stacker
#define NDM7_UD_STACKER_CLAMP_OPER_TIME_MIN     (0x200)
#define NDM7_UD_STACKER_CLAMP_OPER_TIME_MAX     (0x201)
#define NDM7_UD_STACKER_UNCLAMP_OPER_TIME_MIN   (0x202)
#define NDM7_UD_STACKER_UNCLAMP_OPER_TIME_MAX   (0x203)

#define NDM7_UD_UDR_STACKER1_MAX_TRAY_COUNT     (0x220)

#define NDM7_SLOW_UNLOAD_STACKER_OPTION			(0x221)

//=========================================== Stacker
#define NDM7_STK_MAIN_UPDN_WAITTIME		(0x300)
#define NDM7_STK_SUB_UPDN_WAITTIME		(0x301)
#define NDM7_STK_CLAMP_WAITTIME			(0x302)
#define NDM7_STK_CONVEYOR_UNLOAD_STOP_WAIT (0x303)
#define NDM7_STK_CONVEYOR_LOAD_STOP_WAIT (0x304)